// Generated by @arsumbris/type-codegen. Do not edit by hand.
// Source: au-engine type-defs, repo `terminal`.

import type { PaneProjection } from '@arsumbris/au-host-sdk'

/** A branded wikilink string. The brand records the referenced type-def name(s). */
export type Ref<T extends string> = string & { readonly __ref: T }

/** A branded wikilink to a type-def (the def axis of `T*`), distinct from an instance `Ref`. The brand records the def-axis bound. */
export type DefRef<T extends string> = string & { readonly __defRef: T }

export interface Terminal extends Omit<PaneProjection, 'type'> {
  type: 'terminal'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  cwd?: string
  shell?: string
  scrollback?: number
  cursorStyle?: 'bar' | 'block' | 'underline'
  cursorBlink?: boolean
  /** App-session prompt preset. Applied at shell creation; inherit preserves the shell prompt. */
  prompt?: 'inherit' | 'raw' | 'minimal' | 'compact-git' | 'clean' | 'context'
  command?: string
}

export interface TerminalSettings extends Omit<PaneProjection, 'type'> {
  type: 'terminal-settings'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}
