// Generated by @arsumbris/type-codegen. Do not edit by hand.
// Source: au-engine type-defs, repo `sandwich`.

import type { ContainerProjection, ContainerSlot, Intent } from '@arsumbris/au-host-sdk'

/** A branded wikilink string. The brand records the referenced type-def name(s). */
export type Ref<T extends string> = string & { readonly __ref: T }

/** A branded wikilink to a type-def (the def axis of `T*`), distinct from an instance `Ref`. The brand records the def-axis bound. */
export type DefRef<T extends string> = string & { readonly __defRef: T }

export interface Sandwich extends Omit<ContainerProjection, 'type'> {
  type: 'sandwich'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  left?: Ref<'mountable'> | SandwichSlot
  center?: Ref<'mountable'> | SandwichSlot
  right?: Ref<'mountable'> | SandwichSlot
}

/** A sandwich region: the shared slot rules, plus the size and sizing state sandwich renders. */
export interface SandwichSlot extends Omit<ContainerSlot, 'type'> {
  type: 'sandwich-slot'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /**
   * The region's FREE-state extent along sandwich's cross axis, in px. Absent = sandwich's default.
   * Read only when `sizing` is `free`; a `compact` region takes the child's declared width instead.
   */
  size?: number
  /**
   * How the region is sized. `free` renders the child at `size` (the drag width); `compact` sizes
   * the region to the child's smallest declared width (`breakpoints-meta`), so the child renders its
   * own compact form, falling back to `collapsed` when the child declares none; `collapsed` hides the
   * child behind sandwich's strip. Absent = `free`. A collapsed region still has its occupant and rules.
   */
  sizing?: 'free' | 'compact' | 'collapsed'
  /** Minimum free-state width in pixels; compact and collapsed states keep their own extents. */
  minSize?: number
  /** Keep a compact collapse control visible when the region header is hidden. */
  showCollapseControl?: boolean
}

export interface ToggleLeftSidebarIntent extends Omit<Intent, 'type'> {
  type: 'toggle-left-sidebar-intent'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface ToggleRightSidebarIntent extends Omit<Intent, 'type'> {
  type: 'toggle-right-sidebar-intent'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}
