// Pure builder for the component-layer React WRAPPERS (`src/react.ts`, the `./react` sub-output). No
// IO — takes the discovered components (tag + declared fields + declared events) and returns the
// source text. Kept pure so it is unit-testable; discovery (gen-react-wrappers.ts) is the filesystem
// wrapper.

// The output is a REACT-TARGET artifact that emits one `<AuXxx>` component per `<au-*>` tag via
// `makeAuWrapper` (react-runtime). It imports the NEUTRAL interfaces from ./generated and the runtime
// helper — NEVER a component-set element class, so the swappable-set promise holds (a swapped set wins
// the tag in the global registry; the wrapper renders only the tag string).


import { tagToInterface } from './react-jsx-builder.ts'

/** One discovered ui-component: its tag, its declared field (prop) names, its declared event names. */
export interface WrapperComponent {
  tag: string
  fields: string[]
  events: string[]
}

/** An event tag (`au-toggle`) → its React handler prop name (`onAuToggle`). */
export function eventToHandler(eventTag: string): string {
  return `on${tagToInterface(eventTag)}`
}

/** Build the React wrappers source for the given components. Sorted + deduped by tag for a stable emit. */
export function buildReactWrappers(components: WrapperComponent[]): string {
  const rows = [...new Map(components.map((c) => [c.tag, c])).values()].sort((a, b) => a.tag.localeCompare(b.tag))
  const ifaces = rows.map((r) => tagToInterface(r.tag))
  // The wrapper CONST takes the ergonomic name (`AuButton`), so the neutral interface is imported under
  // a `…Shape` alias to avoid a value/type merged-declaration collision.
  const importList = ifaces.map((i) => `${i} as ${i}Shape`).join(', ')

  const blocks = rows
    .map((r) => {
      const iface = tagToInterface(r.tag)
      const eventProps = r.events
        .map((e) => `  ${eventToHandler(e)}?: AuEventHandler`)
        .join('\n')
      const propsBody = eventProps ? `AuHostProps & Omit<${iface}Shape, 'type'> & {\n${eventProps}\n}` : `AuHostProps & Omit<${iface}Shape, 'type'>`
      const fieldsLit = `[${r.fields.map((f) => `'${f}'`).join(', ')}]`
      const eventMapLit = r.events.length
        ? `{ ${r.events.map((e) => `${eventToHandler(e)}: '${e}'`).join(', ')} }`
        : '{}'
      return `/** React wrapper for \`<${r.tag}>\` — renders the tag; props → element properties; events → listeners. */
export type ${iface}Props = ${propsBody}
export const ${iface} = makeAuWrapper<${iface}Props>('${r.tag}', ${fieldsLit}, ${eventMapLit})`
    })
    .join('\n\n')

  return `// Generated by the component-layer React wrapper codegen (\`pnpm gen:react\`). Do not edit by hand.
//
// The \`./react\` sub-output. One \`<AuXxx>\` React component per \`<au-*>\` tag, via \`makeAuWrapper\`
// (react-runtime): it renders the TAG STRING, sets declared props as element PROPERTIES, and wires
// declared events as typed \`onAuXxx\` props. It imports the NEUTRAL interfaces from ./generated and the
// runtime — NEVER a component-set class, so a host-swapped set still wins the tag (live boot-swap).
//
// Also re-exports the JSX augmentation (./react-jsx) so residual intrinsic \`<au-*>\` usage + children
// still type-check. A React consumer imports the wrappers by name:
//   import { ${ifaces[0] ?? 'AuButton'} } from '@arsumbris/au-component-catalog/react'
import './react-jsx.ts'
import { makeAuWrapper, type AuHostProps, type AuEventHandler } from './react-runtime.ts'
import type { ${importList} } from './generated.ts'

export type { AuHostProps, AuEventHandler } from './react-runtime.ts'

${blocks}
`
}
