// Pure builder for the component-layer React JSX augmentation. No IO — takes the discovered
// ui-component tags and returns the augmentation source text. Kept pure so it is unit-testable and
// so discovery (gen-react-jsx.ts) is a thin filesystem wrapper.
//
// The output is a REACT-TARGET artifact: it types each custom-element TAG for TSX by deriving props
// from the NEUTRAL interfaces in ./generated. Svelte/vanilla type custom elements differently, so
// this is a react sub-output, separate from the neutral catalog surface.

/**
 * A ui-component tag (`au-button`) → its PascalCase interface name (`AuButton`), matching the neutral
 * codegen's type→interface naming (kebab segments capitalized, joined). Deterministic for the
 * all-lowercase-kebab tags the ui-component convention mandates (a prop named `type` is banned, and
 * tags carry no internal capitals/acronyms).
 */
export function tagToInterface(tag: string): string {
  return tag
    .split('-')
    .filter((s) => s.length > 0)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('')
}

/**
 * Build the React JSX augmentation source for the given tags. Imports the neutral interfaces from the
 * sibling `./generated`; wraps every tag in ONE `declare module 'react'`. Tags are sorted + deduped
 * for a stable emit.
 */
export function buildReactJsxAugmentation(tags: string[]): string {
  const rows = [...new Set(tags)].sort().map((tag) => ({ tag, iface: tagToInterface(tag) }))
  const imports = rows.map((r) => r.iface).join(', ')
  const lines = rows.map((r) => `      '${r.tag}': Props<${r.iface}>`).join('\n')
  return `// Generated by the component-layer JSX codegen (\`pnpm gen:react\`). Do not edit by hand.
//
// REACT-TARGET augmentation: types each ui-component TAG for TSX by deriving its props from the NEUTRAL
// interfaces in ./generated — for residual INTRINSIC \`<au-*>\` usage + children typing. Svelte/vanilla
// type custom elements differently, so this is the react sub-output only.
//
// The PAVED PATH for React consumers is the generated WRAPPERS (\`./react\`, re-exporting this file), which
// set props as element properties and wire events as typed \`onAuXxx\` props — the two frictions this
// augmentation cannot solve (React sets a dashed-attribute prop unreliably, and does not auto-attach
// custom-element listeners). The wrappers render the tag string and import no set class, so live set-swap
// holds.
import type { ${imports} } from './generated'
import type { DetailedHTMLProps, HTMLAttributes } from 'react'

/** JSX props for a custom-element tag: the neutral data-in props (minus the \`type\` discriminant)
 *  plus the standard React host-element attributes (className / style / ref / children / …). */
type Props<T> = DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement> & Omit<T, 'type'>

declare module 'react' {
  namespace JSX {
    interface IntrinsicElements {
${lines}
    }
  }
}
`
}
