// Generated by @arsumbris/type-codegen. Do not edit by hand.
// Source: au-engine type-defs, repo `dock`.

import type { FrameContainer } from '@arsumbris/au-host-sdk'

/** A branded wikilink string. The brand records the referenced type-def name(s). */
export type Ref<T extends string> = string & { readonly __ref: T }

/** A branded wikilink to a type-def (the def axis of `T*`), distinct from an instance `Ref`. The brand records the def-axis bound. */
export type DefRef<T extends string> = string & { readonly __defRef: T }

export interface Dock extends Omit<FrameContainer, 'type'> {
  type: 'dock'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Bars along the top edge, outermost first. */
  top?: Ref<'bar-projection'>[]
  /** Bars along the bottom edge, outermost first. */
  bottom?: Ref<'bar-projection'>[]
  /** Bars along the left edge, outermost first. */
  left?: Ref<'bar-projection'>[]
  /** Bars along the right edge, outermost first. */
  right?: Ref<'bar-projection'>[]
}
