// Generated by @arsumbris/type-codegen. Do not edit by hand.
// Source: au-engine type-defs, repo `dock`.

import type { ContainerProjection, ContainerSlot, Intent } from '@arsumbris/au-host-sdk'

/** A branded wikilink string. The brand records the referenced type-def name(s). */
export type Ref<T extends string> = string & { readonly __ref: T }

/** A branded wikilink to a type-def (the def axis of `T*`), distinct from an instance `Ref`. The brand records the def-axis bound. */
export type DefRef<T extends string> = string & { readonly __defRef: T }

export interface Dock extends Omit<ContainerProjection, 'type'> {
  type: 'dock'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  top?: Array<Ref<'mountable'> | ContainerSlot>
  bottom?: Array<Ref<'mountable'> | ContainerSlot>
  left?: Array<Ref<'mountable'> | ContainerSlot>
  right?: Array<Ref<'mountable'> | ContainerSlot>
  center?: Ref<'mountable'> | ContainerSlot
}

/**
 * Move the FIRING dock bar to a given edge. Fired by a bar for ITSELF; dock re-parents it.
 * Routed + firer-relative, so never agent-firable.
 */
export interface Reposition extends Omit<Intent, 'type'> {
  type: 'reposition'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Which dock edge to move the firing bar to. */
  edge: 'top' | 'bottom' | 'left' | 'right'
}
