// Generated by @arsumbris/type-codegen. Do not edit by hand.
// Source: au-engine type-defs, repo `agent-sessions`.

import type { PaneProjection } from '@arsumbris/au-host-sdk'
import type { AgentProfile } from '@arsumbris/au-mcp-sdk/generated'

/** A branded wikilink string. The brand records the referenced type-def name(s). */
export type Ref<T extends string> = string & { readonly __ref: T }

/** A branded wikilink to a type-def (the def axis of `T*`), distinct from an instance `Ref`. The brand records the def-axis bound. */
export type DefRef<T extends string> = string & { readonly __defRef: T }

export interface AgentProfiles extends Omit<PaneProjection, 'type'> {
  type: 'agent-profiles'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface AgentRuntimeSettings extends Omit<PaneProjection, 'type'> {
  type: 'agent-runtime-settings'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface AgentSessionHistory extends Omit<PaneProjection, 'type'> {
  type: 'agent-session-history'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  profile?: Ref<'agent-profile'>
  prompt?: 'inherit' | 'raw' | 'minimal' | 'compact-git' | 'clean' | 'context'
}

export interface AgentSessionLauncher extends Omit<PaneProjection, 'type'> {
  type: 'agent-session-launcher'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  profile?: Ref<'agent-profile'>
  prompt?: 'inherit' | 'raw' | 'minimal' | 'compact-git' | 'clean' | 'context'
}

export interface SessionProfile extends Omit<AgentProfile, 'type'> {
  type: 'session-profile'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}
