// Generated by @arsumbris/type-codegen. Do not edit by hand.
// Source: au-engine type-defs, repo `file-tree`.

import type { PaneProjection } from '@arsumbris/au-host-sdk'

/** A branded wikilink string. The brand records the referenced type-def name(s). */
export type Ref<T extends string> = string & { readonly __ref: T }

/** A branded wikilink to a type-def (the def axis of `T*`), distinct from an instance `Ref`. The brand records the def-axis bound. */
export type DefRef<T extends string> = string & { readonly __defRef: T }

export interface FileTree extends Omit<PaneProjection, 'type'> {
  type: 'file-tree'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /**
   * Follow the ACTIVE FILE: when the enclosing selection changes, unfold this tree to that file
   * and scroll it into view. Absent = false, so an unconfigured tree is unchanged.
   *
   * This is DELIBERATELY NOT a global preference. "The active file changed" is STANDING STATE, so
   * it rides the selection channel; whether a given tree FOLLOWS is that tree's own business, and
   * per-instance means two trees can differ (a workspace tree that follows, a scoped tree that
   * does not). The setting belongs to the file tree that owns the reveal behavior.
   *
   * The explicit reveal (a go-to-def) is a different path and needs no field: it arrives as a
   * `ui-intent-highlight` broadcast and is always honoured. This gates only the PASSIVE follow.
   */
  revealActiveFile?: boolean
}
