// Scale test-fixture generator.
//
// Emits a deterministic, TYPED folder-repo for two scale behaviours:
//   - file-open latency at 2-3k typed files
//   - file-tree toggle latency with 100s of files in one folder
//
// The vault is generated, never committed — the repo's .git is already large, and 2.5k files would
// bloat history permanently. This script is the committed source of truth; the output under ./vault
// is gitignored. Determinism: every byte is a pure function of the index + the count knobs, so a
// re-run reproduces the same vault (a scale bug reproduces on the same layout every time).
//
// Usage:  pnpm --filter app gen:scale-vault
// Knobs:  SCALE_SECTIONS (25)  SCALE_PER_SECTION (80)  SCALE_FLAT (500)   -> total = S*P + F
// Output: app/e2e/scale/vault/  — a folder-repo. Point the host gate (or AU_ENTRY) at it; host-bundle
//         and mcp-bundle resolve via the device registry, so the full UI mounts.
//
// The content is typed to stress the daemon's type-graph, not just the file index: an abstract `entry`
// base with two concrete subtypes (`note`, `task`), each instance carrying typed `entry*[]` references
// plus body wikilinks, so validation walks a real reference graph at volume.
import { mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const HERE = dirname(fileURLToPath(import.meta.url)) // app/e2e/scale
const VAULT = join(HERE, 'vault')

const num = (name: string, fallback: number): number => {
  const raw = process.env[name]
  if (raw === undefined) return fallback
  const parsed = Number(raw)
  if (!Number.isInteger(parsed) || parsed < 0) throw new Error(`${name} must be a non-negative integer, got ${raw}`)
  return parsed
}

const SECTIONS = num('SCALE_SECTIONS', 25)
const PER_SECTION = num('SCALE_PER_SECTION', 80)
const FLAT = num('SCALE_FLAT', 500)
const TOTAL = SECTIONS * PER_SECTION + FLAT
const PAD = Math.max(4, String(TOTAL).length)

const name = (i: number): string => `entry-${String(i).padStart(PAD, '0')}`
const CATEGORY = ['idea', 'log', 'ref', 'todo'] as const
const PRIORITY = ['low', 'med', 'high'] as const

// Deterministic related targets: fixed offsets wrapped into [1..TOTAL], self excluded. Every target
// exists, so each typed `entry*[]` reference resolves (no dangling-reference noise in the fixture).
const related = (i: number): number[] => {
  const seen = new Set<number>()
  for (const offset of [1, 3, 13, 137]) {
    const target = ((i - 1 + offset) % TOTAL) + 1
    if (target !== i) seen.add(target)
  }
  return [...seen]
}

const yamlList = (items: readonly string[]): string => items.map(item => `\n  - ${item}`).join('')

const noteBody = (i: number): string => {
  const type = i % 5 === 0 ? 'task' : 'note'
  const title = `Entry ${String(i).padStart(PAD, '0')}`
  const tags = [`tag-${i % 20}`, `bucket-${i % 7}`]
  const rel = related(i).map(t => `"[[${name(t)}]]"`)
  const specific = type === 'task'
    ? `done: ${i % 2 === 0}\npriority: ${PRIORITY[i % PRIORITY.length]}`
    : `category: ${CATEGORY[i % CATEGORY.length]}`
  // Two body wikilinks stress reference resolution + backlinks beyond the typed `related` field.
  const bodyRefs = [name(((i + 41) % TOTAL) + 1), name(((i + 211) % TOTAL) + 1)]
  return `---
type: ${type}
title: ${title}
tags:${yamlList(tags)}
related:${yamlList(rel)}
${specific}
---
# ${title}

Scale-fixture ${type}. Links to [[${bodyRefs[0]}]] and [[${bodyRefs[1]}]].
`
}

const write = (relDir: string, i: number): void => {
  writeFileSync(join(VAULT, relDir, `${name(i)}.md`), noteBody(i))
}

const REPO_YAML = `# Scale test-fixture entry (au.engine.repo). GENERATED by app/e2e/scale/generate.ts — do not edit.
# Framework-free: it owns its own \`entry\`/\`note\`/\`task\` vocabulary, so it declares no deps. The host
# UI is a workspace-composition concern and lives in workspace.yaml discover, never here.
type: au.engine.repo::au-engine
name: scale-vault
description: generated scale test-fixture — ~${TOTAL} typed entries for file-open and file-tree scale profiling
`

const WORKSPACE_YAML = `# Scale test-fixture workspace (au.engine.workspace). GENERATED — do not edit.
# edit: self-lists the containing repo (required). discover: pulls the host UI + agent closures so the
# vault opens as a full workspace; both resolve on disk via the device registry.
type: au.engine.workspace::au-engine
edit:
  - scale-vault
discover:
  - host-bundle
  - mcp-bundle
`

const ENTRY_TYPE = `#: Scale-fixture base entry. Abstract typed content used to stress the type-graph, closure walks and
#: reference resolution at volume. Concrete subtypes: note, task.
abstract: true
fields:
  #: Human title.
  title: String
  #: Free-form tags.
  tags?: String[]
  #: Typed references to related entries. Any concrete subtype satisfies entry* by closure.
  related?: entry*[]
`

const NOTE_TYPE = `#: A scale-fixture note.
extends: entry
fields:
  #: Note category.
  category?: [idea, log, ref, todo]
`

const TASK_TYPE = `#: A scale-fixture task.
extends: entry
fields:
  #: Whether the task is complete.
  done?: Boolean
  #: Task priority.
  priority?: [low, med, high]
`

const generate = (): void => {
  rmSync(VAULT, { recursive: true, force: true })
  mkdirSync(join(VAULT, '.arsumbris'), { recursive: true })
  mkdirSync(join(VAULT, 'type'), { recursive: true })
  writeFileSync(join(VAULT, '.arsumbris', 'repo.yaml'), REPO_YAML)
  writeFileSync(join(VAULT, '.arsumbris', 'workspace.yaml'), WORKSPACE_YAML)
  writeFileSync(join(VAULT, 'type', 'entry.type.yaml'), ENTRY_TYPE)
  writeFileSync(join(VAULT, 'type', 'note.type.yaml'), NOTE_TYPE)
  writeFileSync(join(VAULT, 'type', 'task.type.yaml'), TASK_TYPE)

  let i = 0
  for (let s = 0; s < SECTIONS; s++) {
    const dir = join('content', `section-${String(s).padStart(2, '0')}`)
    mkdirSync(join(VAULT, dir), { recursive: true })
    for (let n = 0; n < PER_SECTION; n++) write(dir, ++i)
  }
  // One flat folder of many siblings, for file-tree toggle latency.
  mkdirSync(join(VAULT, 'content', 'flat'), { recursive: true })
  for (let f = 0; f < FLAT; f++) write(join('content', 'flat'), ++i)

  console.log(`scale-vault: wrote ${i} typed entries to ${VAULT}`)
  console.log(`  ${SECTIONS} sections x ${PER_SECTION} = ${SECTIONS * PER_SECTION} nested + ${FLAT} flat (content/flat)`)
}

generate()
