// Generated by @arsumbris/type-codegen. Do not edit by hand.
// Source: au-engine type-defs, repo `bar`.

import type { BarItemProjection, BarProjection } from '@arsumbris/au-host-sdk'

/** A branded wikilink string. The brand records the referenced type-def name(s). */
export type Ref<T extends string> = string & { readonly __ref: T }

/** A branded wikilink to a type-def (the def axis of `T*`), distinct from an instance `Ref`. The brand records the def-axis bound. */
export type DefRef<T extends string> = string & { readonly __defRef: T }

export interface Bar extends Omit<BarProjection, 'type'> {
  type: 'bar'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Items aligned to the start of the main axis. */
  start?: BarItemProjection[]
  /** Items centered on the main axis. */
  center?: BarItemProjection[]
  /** Items aligned to the end of the main axis. */
  end?: BarItemProjection[]
}
