// Generated by @arsumbris/type-codegen. Do not edit by hand.
// Source: au-engine type-defs, repo `bar`.

import type { ContainerProjection, Projection } from '@arsumbris/au-host-sdk'

/** A branded wikilink string. The brand records the referenced type-def name(s). */
export type Ref<T extends string> = string & { readonly __ref: T }

/** A branded wikilink to a type-def (the def axis of `T*`), distinct from an instance `Ref`. The brand records the def-axis bound. */
export type DefRef<T extends string> = string & { readonly __defRef: T }

export interface Bar extends Omit<ContainerProjection, 'type'> {
  type: 'bar'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  orientation?: 'horizontal' | 'vertical'
  role?: DefRef<'projection'>
  start?: BarItem[]
  center?: BarItem[]
  end?: BarItem[]
}

export interface BarItem {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /**
   * The widget this item renders — a projection instance (inline or referenced). bar mounts it via
   * `host.children.mount`; it is NOT a re-parentable layout child, so it lives inside `bar-item`
   * rather than being a `mountable*` the walker would follow.
   */
  view: Projection | Ref<'projection'>
  /**
   * bar's per-item overflow policy: `false` PINS the item visible (never bunches into "+N more").
   * Absent = eligible to overflow. bar's own placement config, kept off the widget itself.
   */
  overflowEligible?: boolean
}
