// Generated by @arsumbris/type-codegen. Do not edit by hand.
// Source: au-engine type-defs, repo `force-graph`.

import type { PaneProjection } from '@arsumbris/au-host-sdk'

/** A branded wikilink string. The brand records the referenced type-def name(s). */
export type Ref<T extends string> = string & { readonly __ref: T }

/** A branded wikilink to a type-def (the def axis of `T*`), distinct from an instance `Ref`. The brand records the def-axis bound. */
export type DefRef<T extends string> = string & { readonly __defRef: T }

/** A force-directed workspace map of files, references and type relationships. */
export interface ForceGraph extends Omit<PaneProjection, 'type'> {
  type: 'force-graph'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  scope?: 'global' | 'local' | 'saved'
  depth?: number
  query?: string
  colorBy?: 'none' | 'repo' | 'kind'
  sizeBy?: 'degree' | 'uniform'
  showOrphans?: boolean
  edgeColorBy?: 'uniform' | 'kind'
  edgeOpacity?: number
  tracksSelection?: boolean
  labels?: 'off' | 'hover' | 'zoom' | 'always'
  openLabelOpacity?: number
  adjacentLabelOpacity?: number
  highlightOpen?: boolean
  panToSelection?: boolean
  pulseSelection?: boolean
  selectionZoom?: number
  ease?: number
  dimDepth?: number
  nodeScale?: number
  charge?: number
  linkDistance?: number
  linkStrength?: number
}
