// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {identifiers, strings} from "./tokens.ts"
export const parser = LRParser.deserialize({
  version: 14,
  states: "%^O`QUOOOOQO'#Cg'#CgO}QVO'#CdO!]QUO'#CmOOQO'#Cn'#CnOOQO'#Cz'#CzQOQSOOOOQO'#Cf'#CfO!dQSO'#CeOOQO,59O,59OO!iQSO,59OOOQO,59X,59XO!qQSO,59XO`QUO,59PO!yQVO1G.jO#XQSO1G.jOOQO1G.j1G.jO#aQUO1G.sO#hQSO1G.sOOQO1G.s1G.sOOQO1G.k1G.kOOQO,59`,59`OOQO7+$U7+$UO#pQVO7+$UOOQO-E6r-E6rOOQO,59a,59aOOQO7+$_7+$_O$OQUO7+$_OOQO-E6s-E6sOOQO<<Gp<<GpP$VQVO'#CtOOQO<<Gy<<GyP`QUO'#Cu",
  stateData: "$j~OlOSmOSROSSOS~OQPOVQO[PO`ROcSOdSOeTOfTOgTO~OPVOQPOUXO[PO~O_ZO~P`O]]O~OU`O^^O~O^aO_cO~OPVOQPOUfO[PO~OUfO^gO~O_jO~P`O^kO_jO~OPVOQPOUmO[PO~O_oO~P`OPVOQPO[PO~OPQmd~dc~",
  goto: "#QoPPPPPPPPpx!Q!WPPPPPppPPPPP!f!lPPPP!r]TOR]akpQYQVe^gnXWQ^gn[TOR]akpXVQ^gnQ_YRh_Qb[RlbQUOQ[RQd]Viakp",
  nodeNames: "⚠ Identifier ExtendedString LineComment BlockComment JsonText } { Object Property PropertyName String JsonString : , ] [ Array Number JsonNumber ExtendedNumber True False Null",
  maxTerm: 30,
  nodeProps: [
    ["openedBy", 6,"{",15,"["],
    ["closedBy", 7,"}",16,"]"]
  ],
  skippedNodes: [0,3,4],
  repeatNodeCount: 2,
  tokenData: "1k~RqXY#YYZ#YZ[#k[]#k]^#Ypq#Yrs$c{|&x|}*z}!O+P!O!P'[!P!Q-j!Q!R+c!R![-V![!]/c!k!l)m!p!q*n!}#O/h#P#Q/m#Y#Z/r#b#c0a#h#i0x#o#p1a#q#r1f$f$g#k#BY#BZ#k$IS$I_#k$I|$I}#k$I}$JO#k$JT$JU#k$KV$KW#k&FU&FV#k?HT?HU#k~#_Sl~XY#YYZ#Y]^#Ypq#Y~#pZm~Z[#k[]#k$f$g#k#BY#BZ#k$IS$I_#k$I|$I}#k$I}$JO#k$JT$JU#k$KV$KW#k&FU&FV#k?HT?HU#k~$fVpr$crs${s#O$c#O#P%Q#P;'S$c;'S;=`&r<%lO$c~%QO[~~%TXrs$c!P!Q$c#O#P$c#U#V$c#Y#Z$c#b#c$c#f#g$c#h#i$c#i#j%p~%sR!Q![%|!c!i%|#T#Z%|~&PR!Q![&Y!c!i&Y#T#Z&Y~&]R!Q![&f!c!i&f#T#Z&f~&iR!Q![$c!c!i$c#T#Z$c~&uP;=`<%l$c~&{T!O!P'[!Q!R([!R![)[!k!l)m!p!q*n~'_P!Q!['b~'gRd~!Q!['b!g!h'p#X#Y'p~'sR{|'|}!O'|!Q![(S~(PP!Q![(S~(XPd~!Q![(S~(aTd~!O!P'b!g!h'p!z!{(p#X#Y'p#l#m(p~(sR!Q![(|!c!i(|#T#Z(|~)RRd~!Q![(|!c!i(|#T#Z(|~)aSd~!O!P'b!Q![)[!g!h'p#X#Y'p~)pP#b#c)s~)vP#Y#Z)y~)|P#]#^*P~*SP#b#c*V~*YP#]#^*]~*`P#h#i*c~*fP#m#n*i~*nOd~~*qP#T#U*t~*wP!p!q*i~+PO^~~+ST!O!P'[!Q!R+c!R![-V!k!l)m!p!q*n~+jTd~c~!O!P+y!g!h,i!z!{(p#X#Y,i#l#m(p~,ORd~!Q![,X!g!h'p#X#Y'p~,`Rd~c~!Q![,X!g!h,i#X#Y,i~,lR{|,u}!O,u!Q![,{~,xP!Q![,{~-SPd~c~!Q![,{~-^Sd~c~!O!P+y!Q![-V!g!h,i#X#Y,i~-mQz{-s!P!Q.t~-vTOz-sz{.V{;'S-s;'S;=`.n<%lO-s~.YTO!P-s!P!Q.i!Q;'S-s;'S;=`.n<%lO-s~.nOS~~.qP;=`<%l-s~.yUR~OY.tZ].t^$I|.t$JO;'S.t;'S;=`/]<%lO.t~/`P;=`<%l.t~/hO]~~/mO`~~/rO_~~/uP#T#U/x~/{P#`#a0O~0RP#g#h0U~0XP#X#Y0[~0aOf~~0dP#i#j0g~0jP#`#a0m~0pP#`#a0s~0xOg~~0{P#f#g1O~1RP#i#j1U~1XP#X#Y1[~1aOe~~1fOV~~1kOU~",
  tokenizers: [identifiers, strings, 0],
  topRules: {"JsonText":[0,5]},
  dialects: {json5: 156},
  tokenPrec: 161
})
