// Generated by @arsumbris/type-codegen. Do not edit by hand.
// Source: au-engine type-defs, repo `intent`.

import type { Intent, IntentRoutingMeta } from '@arsumbris/au-host-sdk/generated'
import type { Selection } from '@arsumbris/selection'

/** A branded wikilink string. The brand records the referenced type-def name(s). */
export type Ref<T extends string> = string & { readonly __ref: T }

/** A branded wikilink to a type-def (the def axis of `T*`), distinct from an instance `Ref`. The brand records the def-axis bound. */
export type DefRef<T extends string> = string & { readonly __defRef: T }

export interface ChoosePaneIntent extends Omit<Intent, 'type'> {
  type: 'choose-pane-intent'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

/** Close the focused view. A host-handled command. */
export interface CloseViewIntent extends Omit<Intent, 'type'> {
  type: 'close-view-intent'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

/**
 * Toggle the collapse of the FIRING view's region. Fired by a region occupant for ITSELF
 * (e.g. the rail's collapse toggle); the enclosing sandwich narrows/expands the region that
 * holds the firer. No payload: the firer is implicit. Routed + firer-relative.
 */
export interface CollapseRegion extends Omit<Intent, 'type'> {
  type: 'collapse-region'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface CreateFileIntent extends Omit<Intent, 'type'> {
  type: 'create-file-intent'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

/** Delete the selected composition file. A host-handled command. */
export interface DeleteCompositionIntent extends Omit<Intent, 'type'> {
  type: 'delete-composition-intent'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface EditsCompositionConfigMeta {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  edits: DefRef<'composition-config'>[]
}

export interface FocusDownIntent extends Omit<Intent, 'type'> {
  type: 'focus-down-intent'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  target?: String
}

export interface FocusLeftIntent extends Omit<Intent, 'type'> {
  type: 'focus-left-intent'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  target?: String
}

export interface FocusRightIntent extends Omit<Intent, 'type'> {
  type: 'focus-right-intent'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  target?: String
}

export interface FocusUpIntent extends Omit<Intent, 'type'> {
  type: 'focus-up-intent'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  target?: String
}

/**
 * Whether an AGENT may fire this intent over the agent-host socket. Default-deny: an
 * intent with no such block is refused. Separate from routing metadata, which says how
 * the host dispatches an intent rather than who may send it.
 */
export interface IntentAgentMeta {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /**
   * `true` = an agent may fire this intent. `false` = it may not, and saying so
   * explicitly is the point — the field is REQUIRED inside the block, so declaring the
   * block is an explicit yes or an explicit no, never a shrug. A refusal still stands
   * when the intent's payload is privileged by shape.
   */
  firable: boolean
}

export interface KeepTabIntent extends Omit<Intent, 'type'> {
  type: 'keep-tab-intent'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface NewTabIntent extends Omit<Intent, 'type'> {
  type: 'new-tab-intent'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface NextTabIntent extends Omit<Intent, 'type'> {
  type: 'next-tab-intent'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

/**
 * The content-renderer locator for a ui-notification subtype: the module + export the host loads
 * to draw the toast's content into the host frame (selected by the fired notification's type).
 */
export interface NotificationContentMeta {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The ESM entry, relative to the owning package root (the built dist module). */
  entry: string
  /**
   * The named export that IS the content renderer — a (notification, element, fireAction) => void
   * the host calls to fill the toast. Default `render`.
   */
  export?: string
}

export interface OpenFileDialogIntent extends Omit<Intent, 'type'> {
  type: 'open-file-dialog-intent'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

/**
 * Open a target in the focused container. Routed + ambient: the MRU-focused
 * container that handles open-intent claims it and decides HOW (bento a tab, a
 * canvas a node); `mode` disposes of the tab lifecycle.
 */
export interface OpenIntent extends Omit<Intent, 'type'> {
  type: 'open-intent'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** What to open, a selection. A file-selection names the file (path + optional range). */
  target: Selection | Ref<'selection'>
  /**
   * How the container disposes the open. OPTIONAL: absent means the firer has no
   * opinion and the CONTAINER decides (its own default, which a composition may
   * author). Present means a gesture was explicit. transient = a reused/replaced
   * preview; permanent = a persistent tab (double-click or an edit promotes here);
   * preview-pin = pin the current preview, then open this as a new preview
   * (cmd/ctrl+click, keep + peek next).
   */
  mode?: 'transient' | 'permanent' | 'preview-pin'
  /**
   * The chosen VIEWER, a projection type reference. OPTIONAL: absent means the viewer resolves through
   * the explicit ladder (`opens-meta` ELIGIBILITY, then a composition viewer-default, the sole eligible
   * viewer, else the host chooser asks); present (an "Open with X" pick) names the viewer to use and
   * wins the ladder outright. A DEF-REF, so it is verifiable against the type graph even though intents
   * are never persisted; and a POINTER, not a config, so the socket gate leaves open-intent firable.
   */
  with?: DefRef<'projection'>
}

/**
 * Place a caller-supplied projection instance as a new pane. Routed + ambient: the
 * MRU-focused container that handles it claims it and splits the pane in. Its payload
 * is a projection CONFIG, so it is never agent-firable.
 */
export interface OpenPaneIntent extends Omit<Intent, 'type'> {
  type: 'open-pane-intent'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /**
   * The projection instance to mount, OPAQUE to the intent vocab (the container interprets it).
   * `opaque` is the privileged payload: arbitrary mountable content, which is why the verb is
   * never firable, and it is why the TS type is `unknown`.
   */
  pane: unknown
}

export interface PreviousTabIntent extends Omit<Intent, 'type'> {
  type: 'previous-tab-intent'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

/**
 * Promote the FIRING view from transient to permanent. Fired by a transient view
 * for ITSELF (e.g. an editor on first edit); the firer's container promotes its
 * tab/node. No payload: the firer is implicit (the channel delivers its identity).
 * Routed + firer-relative.
 */
export interface PromoteIntent extends Omit<Intent, 'type'> {
  type: 'promote-intent'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

/**
 * Reveal (focus / activate) an already-mounted pane by its id. Routed + ambient: the container that
 * holds the pane claims and activates it; every other container declines.
 */
export interface RevealPaneIntent extends Omit<Intent, 'type'> {
  type: 'reveal-pane-intent'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The stable `^:` id of the pane to reveal — a `surfaceId` from the open-surfaces index. */
  paneId: string
}

/** Save the active composition under a new name. A host-handled command. */
export interface SaveCompositionAsIntent extends Omit<Intent, 'type'> {
  type: 'save-composition-as-intent'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The new composition's name. */
  name: string
}

/** Save the active composition to its file. A host-handled command. */
export interface SaveCompositionIntent extends Omit<Intent, 'type'> {
  type: 'save-composition-intent'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

/** Save the focused thing — the focused editor saves its file, else the host saves the composition. */
export interface SaveIntent extends Omit<Intent, 'type'> {
  type: 'save-intent'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface SearchFilesIntent extends Omit<Intent, 'type'> {
  type: 'search-files-intent'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface SearchOpenPanesIntent extends Omit<Intent, 'type'> {
  type: 'search-open-panes-intent'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface SearchProjectionsIntent extends Omit<Intent, 'type'> {
  type: 'search-projections-intent'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface SelectTabIntent extends Omit<Intent, 'type'> {
  type: 'select-tab-intent'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Visible tab number 1–8; 9 selects the last tab. */
  key: String
}

/**
 * Reveal-or-create a pane of a given type. Routed + ambient: the MRU-focused container
 * that handles it focuses a matching pane or creates a bare one. Agent-firable: it names
 * a type, never a config.
 */
export interface ShowPaneIntent extends Omit<Intent, 'type'> {
  type: 'show-pane-intent'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /**
   * The projection type name to reveal-or-create. A bare type name; the container
   * instantiates `{ type: paneType }`, authoring no other fields.
   */
  paneType: string
}

export interface SplitDownIntent extends Omit<Intent, 'type'> {
  type: 'split-down-intent'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface SplitRightIntent extends Omit<Intent, 'type'> {
  type: 'split-right-intent'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

/** Toggle the command palette open or closed. */
export interface ToggleCommandPaletteIntent extends Omit<Intent, 'type'> {
  type: 'toggle-command-palette-intent'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

/**
 * Toggle between quiet container frames and fully visible wrapper headers. A local view preference;
 * the composition and its nesting remain unchanged.
 */
export interface ToggleContainerNestingIntent extends Omit<Intent, 'type'> {
  type: 'toggle-container-nesting-intent'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

/** Temporarily reveal or hide pane headers without changing authored layout settings. */
export interface TogglePaneHeadersIntent extends Omit<Intent, 'type'> {
  type: 'toggle-pane-headers-intent'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

/**
 * Highlight a target wherever it is shown. BROADCAST: every open projection that
 * handles it highlights ITS OWN copy. `mode` chooses passive highlight vs
 * scroll-into-view. Fired by the UI or, across the bridge, the agent.
 */
export interface UiIntentHighlight extends Omit<Intent, 'type'> {
  type: 'ui-intent-highlight'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /**
   * What to highlight, a selection (a file-selection with an optional range).
   * Reuses the selection vocab.
   */
  target: Selection | Ref<'selection'>
  /**
   * show-if-visible = highlight only where already on-screen (passive);
   * reveal-if-exists = each holder scrolls its OWN viewport to bring the target
   * into view (per-copy, no single winner).
   */
  mode: 'show-if-visible' | 'reveal-if-exists'
}

/**
 * Surface a transient message to the human. BROADCAST: every mounted surfacer that
 * handles it shows it ITS OWN way (a toast, a status flash), no focus or routing.
 * Fired by the session (agent) or any node. `severity` tags it; `actions` are optional
 * labeled follow-ups the surfacer renders + fires.
 */
export interface UiNotification extends Omit<Intent, 'type'> {
  type: 'ui-notification'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /**
   * How urgent — info (neutral), warn (attention), error (something failed). The
   * surfacer styles by it (e.g. a severity glyph / color).
   */
  severity: 'info' | 'warn' | 'error'
  /** The human-facing message text. */
  message: string
  /**
   * Optional labeled follow-up actions. The surfacer renders each as an affordance and
   * FIRES its embedded intent on activation. Omit for a plain notification.
   */
  actions?: UiNotificationAction[]
}

/**
 * A labeled follow-up on a notification: a `label` the surfacer shows and the `intent`
 * it fires on activation. The vocab does not interpret the intent (opaque, inline-or-ref).
 */
export interface UiNotificationAction {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The button/affordance text the surfacer renders. */
  label: string
  /**
   * The intent fired when the human activates this action (inline or a referenced
   * intent instance). Opaque to this vocab — the surfacer fires it via host.intent.fire.
   */
  intent: Intent | Ref<'intent'>
}

export const CHOOSE_PANE_INTENT_ROUTING = { kind: 'routed', dispatch: 'ambient' } as const satisfies Omit<IntentRoutingMeta, 'type'>

export const CLOSE_VIEW_INTENT_ROUTING = { kind: 'routed', dispatch: 'ambient' } as const satisfies Omit<IntentRoutingMeta, 'type'>

export const COLLAPSE_REGION_ROUTING = { kind: 'routed', dispatch: 'firer-relative' } as const satisfies Omit<IntentRoutingMeta, 'type'>

export const CREATE_FILE_INTENT_ROUTING = { kind: 'routed', dispatch: 'ambient' } as const satisfies Omit<IntentRoutingMeta, 'type'>

export const DELETE_COMPOSITION_INTENT_ROUTING = { kind: 'routed', dispatch: 'ambient' } as const satisfies Omit<IntentRoutingMeta, 'type'>

export const FOCUS_DOWN_INTENT_ROUTING = { kind: 'routed', dispatch: 'ambient' } as const satisfies Omit<IntentRoutingMeta, 'type'>

export const FOCUS_LEFT_INTENT_ROUTING = { kind: 'routed', dispatch: 'ambient' } as const satisfies Omit<IntentRoutingMeta, 'type'>

export const FOCUS_RIGHT_INTENT_ROUTING = { kind: 'routed', dispatch: 'ambient' } as const satisfies Omit<IntentRoutingMeta, 'type'>

export const FOCUS_UP_INTENT_ROUTING = { kind: 'routed', dispatch: 'ambient' } as const satisfies Omit<IntentRoutingMeta, 'type'>

export const KEEP_TAB_INTENT_ROUTING = { kind: 'routed', dispatch: 'ambient' } as const satisfies Omit<IntentRoutingMeta, 'type'>

export const NEW_TAB_INTENT_ROUTING = { kind: 'routed', dispatch: 'ambient' } as const satisfies Omit<IntentRoutingMeta, 'type'>

export const NEXT_TAB_INTENT_ROUTING = { kind: 'routed', dispatch: 'ambient' } as const satisfies Omit<IntentRoutingMeta, 'type'>

export const OPEN_FILE_DIALOG_INTENT_ROUTING = { kind: 'routed', dispatch: 'ambient' } as const satisfies Omit<IntentRoutingMeta, 'type'>

export const OPEN_INTENT_ROUTING = { kind: 'routed', dispatch: 'ambient' } as const satisfies Omit<IntentRoutingMeta, 'type'>

export const OPEN_PANE_INTENT_ROUTING = { kind: 'routed', dispatch: 'ambient' } as const satisfies Omit<IntentRoutingMeta, 'type'>

export const PREVIOUS_TAB_INTENT_ROUTING = { kind: 'routed', dispatch: 'ambient' } as const satisfies Omit<IntentRoutingMeta, 'type'>

export const PROMOTE_INTENT_ROUTING = { kind: 'routed', dispatch: 'firer-relative' } as const satisfies Omit<IntentRoutingMeta, 'type'>

export const REVEAL_PANE_INTENT_ROUTING = { kind: 'routed', dispatch: 'ambient' } as const satisfies Omit<IntentRoutingMeta, 'type'>

export const SAVE_COMPOSITION_AS_INTENT_ROUTING = { kind: 'routed', dispatch: 'ambient' } as const satisfies Omit<IntentRoutingMeta, 'type'>

export const SAVE_COMPOSITION_INTENT_ROUTING = { kind: 'routed', dispatch: 'ambient' } as const satisfies Omit<IntentRoutingMeta, 'type'>

export const SAVE_INTENT_ROUTING = { kind: 'routed', dispatch: 'ambient' } as const satisfies Omit<IntentRoutingMeta, 'type'>

export const SEARCH_FILES_INTENT_ROUTING = { kind: 'routed', dispatch: 'ambient' } as const satisfies Omit<IntentRoutingMeta, 'type'>

export const SEARCH_OPEN_PANES_INTENT_ROUTING = { kind: 'routed', dispatch: 'ambient' } as const satisfies Omit<IntentRoutingMeta, 'type'>

export const SEARCH_PROJECTIONS_INTENT_ROUTING = { kind: 'routed', dispatch: 'ambient' } as const satisfies Omit<IntentRoutingMeta, 'type'>

export const SELECT_TAB_INTENT_ROUTING = { kind: 'routed', dispatch: 'ambient' } as const satisfies Omit<IntentRoutingMeta, 'type'>

export const SHOW_PANE_INTENT_ROUTING = { kind: 'routed', dispatch: 'ambient' } as const satisfies Omit<IntentRoutingMeta, 'type'>

export const SPLIT_DOWN_INTENT_ROUTING = { kind: 'routed', dispatch: 'ambient' } as const satisfies Omit<IntentRoutingMeta, 'type'>

export const SPLIT_RIGHT_INTENT_ROUTING = { kind: 'routed', dispatch: 'ambient' } as const satisfies Omit<IntentRoutingMeta, 'type'>

export const TOGGLE_COMMAND_PALETTE_INTENT_ROUTING = { kind: 'routed', dispatch: 'ambient' } as const satisfies Omit<IntentRoutingMeta, 'type'>

export const TOGGLE_CONTAINER_NESTING_INTENT_ROUTING = { kind: 'routed', dispatch: 'ambient' } as const satisfies Omit<IntentRoutingMeta, 'type'>

export const TOGGLE_PANE_HEADERS_INTENT_ROUTING = { kind: 'routed', dispatch: 'ambient' } as const satisfies Omit<IntentRoutingMeta, 'type'>

export const UI_INTENT_HIGHLIGHT_ROUTING = { kind: 'broadcast' } as const satisfies Omit<IntentRoutingMeta, 'type'>

export const UI_NOTIFICATION_ROUTING = { kind: 'broadcast' } as const satisfies Omit<IntentRoutingMeta, 'type'>
