// Generated by @arsumbris/type-codegen. Do not edit by hand.
// Source: au-engine type-defs, repo `tabs`.

import type { ContainerSlot, GroupingContainer } from '@arsumbris/au-host-sdk'

/** A branded wikilink string. The brand records the referenced type-def name(s). */
export type Ref<T extends string> = string & { readonly __ref: T }

/** A branded wikilink to a type-def (the def axis of `T*`), distinct from an instance `Ref`. The brand records the def-axis bound. */
export type DefRef<T extends string> = string & { readonly __defRef: T }

export interface Tabs extends Omit<GroupingContainer, 'type'> {
  type: 'tabs'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** A persistent start view: fills an empty group, then becomes a compact header above its tabs. */
  startView?: Ref<'pane-projection'>
  /** Keep the start view compact when this projection is open elsewhere in the composition. */
  startViewCompactWhen?: DefRef<'projection'>
  tabs: Array<Ref<'mountable'> | ContainerSlot>
  /**
   * The active tab, named by its child's `^:` id — a SOFT pointer, not a validated ref. Falls back to the
   * first tab when absent or unresolved, e.g. when the active tab was a transient preview the substrate
   * dropped at serialize. Identity, not position, so a dropped/removed tab never mis-selects a sibling.
   */
  activeTab?: string
  /** Placeholder for this group when empty. Other groups keep their own defaults. */
  emptyPlaceholder?: DefRef<'placeholder-projection'>
  /** Replace this group's sole configured placeholder on an explicit open-pane action. */
  replaceEmptyPlaceholderOnOpen?: boolean
  /**
   * How THIS group opens a file when the fired intent carries NO mode — that is, when the firer
   * had no opinion, the normal case for a caller with no preference.
   * An EXPLICIT mode on the intent always wins; this only answers the absent case.
   * Absent = `transient`, suitable for browsing with a single click,
   * so an unconfigured group opens transient tabs.
   * Per-instance: a reference panel and a working editor can choose different defaults.
   * `preview-pin` is deliberately NOT admissible here, so this enum is a SUBSET of the intent's
   * three: it is a GESTURE verb ("pin what I am previewing, peek the next"), which is meaningless
   * as a standing default.
   */
  defaultOpenMode?: 'transient' | 'permanent'
  /**
   * Where a newly opened file tab is inserted relative to its source tab in THIS group.
   * If the source is outside the group or no longer present, use the active tab instead.
   * An empty group inserts at zero. Existing-file activation and preview reuse stay in place.
   * Absent preserves before-source behavior; compositions may explicitly choose after-source.
   */
  newTabPosition?: 'before-source' | 'after-source'
}
