// Generated by @arsumbris/type-codegen. Do not edit by hand.
// Source: au-engine type-defs, repo `au-component-catalog`.

import type { Keystroke } from '@arsumbris/au-host-sdk'
import type { UiComponent } from '@arsumbris/component-contract'

/** A branded wikilink string. The brand records the referenced type-def name(s). */
export type Ref<T extends string> = string & { readonly __ref: T }

/** A branded wikilink to a type-def (the def axis of `T*`), distinct from an instance `Ref`. The brand records the def-axis bound. */
export type DefRef<T extends string> = string & { readonly __defRef: T }

/**
 * The interface for <au-accordion>: a disclosure group over slotted <au-accordion-item>s — single/multiple
 * open, flush/card/inline, keyboard roving. Emits `au-change {open}` (the open item values).
 */
export interface AuAccordion extends Omit<UiComponent, 'type'> {
  type: 'au-accordion'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /**
   * Open policy. `multiple` (default, items open independently) or `single` (opening one closes its siblings).
   * (Named `mode`, not `type` — `type` is the reserved codegen discriminant.)
   */
  mode?: 'single' | 'multiple'
  /** Container treatment. `flush` (default, hairline-divided rows in a frame) / `card` / `inline` (bordered blocks). */
  variant?: 'flush' | 'card' | 'inline'
  /** Row rhythm. `compact` (32) / `default` (40) / `relaxed` (48) header min-height. */
  density?: 'compact' | 'default' | 'relaxed'
  /** In `single` mode, allow closing the one open item by clicking it again. */
  collapsible?: boolean
}

/**
 * The interface for <au-accordion-item>: one disclosure — header (icon + label + meta slot + chevron) over
 * a collapsible panel (default slot). Standalone or grouped. Emits `au-toggle {value, open}`.
 */
export interface AuAccordionItem extends Omit<UiComponent, 'type'> {
  type: 'au-accordion-item'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Stable identity — drives open state, keys the group, wires header↔panel aria. */
  value?: string
  /** The header label (title line). */
  label?: string
  /** Optional leading au-icon glyph NAME (a string). */
  icon?: string
  /** A muted second line under the label. */
  sublabel?: string
  /** Non-toggleable, dimmed, aria-disabled. */
  disabled?: boolean
  /** Resting selected posture — a surface lift (never a leading bar). */
  selected?: boolean
  /** Whether the panel is open. Standalone it self-toggles; in a group the group drives it. */
  open?: boolean
  /** Container treatment — normally SET BY THE GROUP. `flush` (default) / `card` / `inline`. */
  variant?: 'flush' | 'card' | 'inline'
  /** Row rhythm — normally SET BY THE GROUP. `compact` / `default` / `relaxed`. */
  density?: 'compact' | 'default' | 'relaxed'
}

/**
 * <au-badge> — a compact sans-serif count, short label or bare status dot. Counts use
 * tabular digits and rounded ends; labels can wrap and grow with larger text. Semantic tones
 * tint the surface and foreground using theme roles. Content is the default slot; non-interactive.
 */
export interface AuBadge extends Omit<UiComponent, 'type'> {
  type: 'au-badge'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** label / count render the slotted content; dot collapses to a bare marker (no content). */
  variant?: 'label' | 'count' | 'dot'
  /** The status tone. ok / warn / danger paint the fill; ink is the neutral default. */
  tone?: 'ink' | 'ok' | 'warn' | 'danger'
}

/**
 * Text-role fallbacks match the base ink palette without token stylesheets.
 * The interface for <au-banner>: a persistent inline message surface — tone dot/glyph + heading + message,
 * optional action slot + dismiss. tone / variant / placement / emphasis. Emits `au-dismiss`.
 */
export interface AuBanner extends Omit<UiComponent, 'type'> {
  type: 'au-banner'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Severity, on the leading dot/glyph only. `neutral` (default) / `info` (grey, not a hue) / `ok` / `warn` / `danger`. */
  tone?: 'neutral' | 'info' | 'ok' | 'warn' | 'danger'
  /** `inline` (default, a trailing action cluster) or `block` (a richer callout, actions drop to their own row). */
  variant?: 'inline' | 'block'
  /** `contained` (default) or `docked` (a full-bleed edge strip, reads as chrome). */
  placement?: 'contained' | 'docked'
  /** `flat` (mono, default) or `tint` (opt-in danger/warn surface whisper + tone ring; reserve for a blocking banner). */
  emphasis?: 'flat' | 'tint'
  /** Optional bold heading line above the message. */
  heading?: string
  /** The message text (data-driven, a string). Composed action controls go in the `action` slot. */
  message?: string
  /**
   * Optional leading au-icon glyph NAME (a string) replacing the tone dot; it inherits the tone colour. For
   * a live / pending banner, slot an au-spinner / au-status-dot into the `icon` slot instead (it wins).
   */
  icon?: string
  /** Show a trailing close affordance. Emits `au-dismiss` on press. */
  dismissible?: boolean
}

/**
 * The interface for <au-breadcrumb>: a path nav over `items` (au-breadcrumb-item[]). Earlier crumbs are
 * buttons (emit `au-navigate {index, value, label}`), the last is the current page. `maxItems` collapses
 * the middle to an ellipsis.
 * Hover and press use shared chrome interaction fills; keyboard focus uses the shared inset outline.
 */
export interface AuBreadcrumb extends Omit<UiComponent, 'type'> {
  type: 'au-breadcrumb'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The path, root → leaf. The consumer owns it; the last item is the current page. */
  items?: AuBreadcrumbItem[]
  /** The divider between segments. */
  separator?: 'slash' | 'chevron'
  /** Collapse the middle to an `…` once the path exceeds this many segments (keeps first + last N). */
  maxItems?: number
  /** Accessible name for the nav landmark. */
  label?: string
}

/**
 * One <au-breadcrumb> segment: label, an optional leading au-icon glyph NAME, an optional value, and
 * an interactive flag (earlier crumbs are buttons by default).
 */
export interface AuBreadcrumbItem {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The visible segment text. */
  label: string
  /** Optional leading au-icon glyph NAME (a string, not a framework node). */
  icon?: string
  /** A stable value the consumer maps back to on `au-navigate`. */
  value?: string
  /** An earlier crumb is an interactive button by default; set false for a quiet static crumb. */
  interactive?: boolean
}

/**
 * The interface for <au-button>. A leaf component: data-in props, one event out, default
 * slot for its label. Set-independent — consumers type against this, never against a set.
 */
export interface AuButton extends Omit<UiComponent, 'type'> {
  type: 'au-button'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Visual role: solid / ghost / outline / cta (monochrome) + danger (a destructive-action extension). */
  variant?: 'solid' | 'ghost' | 'outline' | 'cta' | 'danger'
  /** Size step. sm/md/lg = 28/32/40, parity with au-input. Default md. */
  size?: 'sm' | 'md' | 'lg'
  /** Non-interactive + de-emphasized. Also reflected as the `disabled` state. */
  disabled?: boolean
  /** Busy: shows a progress affordance and suppresses activation. Reflected as `loading`. */
  loading?: boolean
  /** Leading icon NAME (not a framework element). Slot `leading` for arbitrary content. */
  icon?: string
}

/**
 * <au-card> — a content container. `variant` surface (a raised elevation-3 panel, default) or outline
 * (a transparent hairline strip for metadata). `interactive` opts into hover / focus affordances and
 * keyboard focusability; `roomy` steps the padding up. Content is the default slot, projected in.
 */
export interface AuCard extends Omit<UiComponent, 'type'> {
  type: 'au-card'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** surface = raised elevation-3 panel (default); outline = transparent hairline strip. */
  variant?: 'surface' | 'outline'
  /** Opt into hover / focus affordances and keyboard focusability (tabindex). */
  interactive?: boolean
  /** Step the padding up (space-5 instead of space-4). */
  roomy?: boolean
}

/**
 * The interface for <au-checkbox>: a checkbox — a token box with a check (checked) or dash
 * (indeterminate) glyph, an optional label. Form-associated. Emits `au-change {checked}`.
 */
export interface AuCheckbox extends Omit<UiComponent, 'type'> {
  type: 'au-checkbox'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Whether the box is checked. Form-associated (participates in a native form + reset). */
  checked?: boolean
  /** The "mixed" state — the box shows a dash and reports aria mixed. A user toggle clears it. */
  indeterminate?: boolean
  /** Non-interactive + de-emphasized. Reflected as the `disabled` state. */
  disabled?: boolean
  /** Box size step. `md` (default), `sm` (dense lists), `lg` (roomy). The glyph scales. */
  size?: 'sm' | 'md' | 'lg'
  /** Text beside the box (the whole control is the clickable label). Omitted → set an aria-label. */
  label?: string
}

/**
 * The interface for <au-chevron>: the disclosure arrow (section / nav-group / tree row / select trigger).
 * `open` rotates it from pointing-right to pointing-down. Emits `au-activate` on press.
 * Hover and press use shared chrome interaction fills; keyboard focus uses the shared inset outline.
 */
export interface AuChevron extends Omit<UiComponent, 'type'> {
  type: 'au-chevron'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Consumer-owned disclosure state — true rotates right to down and sets aria-expanded; activation emits an event without changing this prop. */
  open?: boolean
  /** Accessible label. Missing or blank uses Collapse / Expand by `open`. */
  label?: string
  /** Non-interactive + de-emphasized; suppresses activation. */
  disabled?: boolean
}

/**
 * <au-chip> — a small labelled leaf with an optional remove affordance. Data-driven label + variant;
 * emits au-remove when the (optional) remove control is activated.
 */
export interface AuChip extends Omit<UiComponent, 'type'> {
  type: 'au-chip'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The chip text. Render-resilient: absent renders empty. */
  label?: string
  /** Visual role. */
  variant?: 'neutral' | 'accent' | 'danger'
  /** Show a remove (×) affordance that emits au-remove. */
  removable?: boolean
}

/**
 * <au-chord-input> — a keybind CHORD-CAPTURE field. Focus it and press a shortcut; it canonicalizes the
 * keydown (the shared au-host-sdk canonicalizer, so a captured chord matches what the dispatcher produces),
 * shows it as an <au-kbd> chip, and emits `au-chord-change` with the structured keystroke record the keymap
 * editor writes. While focused it marks itself `data-au-keycapture` so the keybind gate yields every keystroke
 * to it (⌘S included). v1 captures a SINGLE keystroke (one chord step). The `chord` value is a PROPERTY
 * (complex data), never an attribute. Field frame + focus ring mirror au-input; the chord renders via au-kbd.
 */
export interface AuChordInput extends Omit<UiComponent, 'type'> {
  type: 'au-chord-input'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The current chord value, a list of keystroke records. Set as a PROPERTY (complex data). Omit for empty. */
  chord?: Keystroke[]
  /** Placeholder shown when empty and not capturing. Default "Set a shortcut". */
  placeholder?: string
  /** Disable capture and focus. Default false. */
  disabled?: boolean
}

/**
 * The interface for <au-close-button>: the ✕ affordance on tabs / chips / panels / modals.
 * Emits `au-activate` on press.
 * Hover and press use shared chrome interaction fills; keyboard focus uses the shared inset outline.
 */
export interface AuCloseButton extends Omit<UiComponent, 'type'> {
  type: 'au-close-button'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** `danger` tints the hover glyph with the danger token (a close that destroys). Default neutral. */
  tone?: 'neutral' | 'danger'
  /** Accessible label. Missing or blank uses "Close". Supply a contextual name when several close actions share a surface. */
  label?: string
  /** Non-interactive + de-emphasized; suppresses activation. */
  disabled?: boolean
}

/**
 * Copy confirms success after the clipboard write resolves; unavailable or rejected writes expose a retry label.
 * <au-code-block> — a framed monospace code surface with a copy affordance. `code` renders a plain
 * <pre>; `language` shows a chip; `copy` (default true) shows the copy button. Slot composed rows instead of `code`.
 */
export interface AuCodeBlock extends Omit<UiComponent, 'type'> {
  type: 'au-code-block'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The source to render as a plain <pre>. Omit and slot composed rows instead. */
  code?: string
  /** Optional language label, shown as a chip in the head. */
  language?: string
  /** Show the copy button. Default true. */
  copy?: boolean
  /** Explicit text to copy. Defaults to `code`; required when slotting composed rows. */
  copyText?: string
}

/**
 * <au-code-sample> — a MOCK code editor (themed gutter + syntax-coloured lines) rendered from the
 * `--au-code-*` / `--au-editor-*` token ladder. The real CodeMirror editor wears the SAME tokens, so
 * this is the surface to dial the syntax + chrome palette: edit the tokens, watch it here, reload the
 * app. Not the editor itself, just a faithful swatch.
 */
export interface AuCodeSample extends Omit<UiComponent, 'type'> {
  type: 'au-code-sample'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The 1-based line rendered as the active line (gutter highlight + wash). Default 5. */
  activeLine?: number
}

/**
 * Axis controls compose au-slider and emit color strings through the picker contract.
 * Field text fallbacks match the base ink palette; transparency checkerboard styling is separate.
 * The interface for <au-color-picker>: a swatch trigger opening an OKLCH popover (hex + L/C/H/A
 * sliders). Emits `au-change {value}` (an oklch() string). The popover claims host.overlay.
 */
export interface AuColorPicker extends Omit<UiComponent, 'type'> {
  type: 'au-color-picker'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /**
   * The current colour — an `oklch()` string (authored token notation) or a hex (`#rrggbb`/`#rrggbbaa`).
   * A non-colour value (e.g. a `var(--au-*)`) still renders the swatch; the sliders sit at neutral.
   */
  value?: string
  /** Show the alpha slider, including live changes while the popup is open. Default true. Reflected as the `alpha` state. */
  alpha?: boolean
  /** Trigger swatch size. sm/md/lg. Default md. */
  size?: 'sm' | 'md' | 'lg'
  /** Accessible name for the trigger + popover. */
  label?: string
}

/**
 * The interface for <au-combobox>: a value-picker that filters — a field/trigger + a filterable
 * Text-role fallbacks match the base palette when token stylesheets are absent.
 * listbox over `options` (au-combobox-option[]) drawn through host.overlay. `trigger` or `inline` mode,
 * single or `multiple`. Form-associated. Emits `au-change` ({value}|{values}), `au-input` {query},
 * `au-create` {query}. Keyboard listbox nav (Arrow/Home/End/Enter/Escape/Tab).
 */
export interface AuCombobox extends Omit<UiComponent, 'type'> {
  type: 'au-combobox'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The option model. The consumer owns it; the control renders, filters + navigates. */
  options?: AuComboboxOption[]
  /** The chosen value (single-select). Empty → the placeholder shows. Form-associated. */
  value?: string
  /** The committed values (multi-select) — rendered as chips in the field. JS property (`.values`). */
  values?: string[]
  /** Multi-select: pick toggles membership, the popup stays open across picks, chips fill the field. */
  multiple?: boolean
  /** `trigger` (default — the search lives in the popup) or `inline` (the field IS the filter). */
  mode?: 'trigger' | 'inline'
  /** Field placeholder when nothing is committed. */
  placeholder?: string
  /** Placeholder for the in-popup search field (trigger mode). */
  searchPlaceholder?: string
  /** Whether typing narrows the list at all (default on). */
  filterable?: boolean
  /**
   * Remote filter: the control stops filtering internally (treats `options` as already-filtered) and
   * reports each keystroke via `au-input`. Pair with `loading`.
   */
  remote?: boolean
  /** Async: swaps the search magnifier for a spinner and shows skeleton rows / dims the prior set. */
  loading?: boolean
  /** Offer a monochrome “Add ‘<query>’” row when the query matches no existing label. Emits `au-create`. */
  creatable?: boolean
  /** Non-interactive + de-emphasized. Reflected. */
  disabled?: boolean
  /** Accessible name for the field + listbox. */
  label?: string
  /** Whether the popup is open. Reflected — set it to seed an open preview. */
  open?: boolean
  /** The live filter query. Seed it to show a filtered / no-match / create preview. */
  query?: string
}

/**
 * One <au-combobox> option: value (keys select + matches the field value), label, an optional leading
 * glyph (an au-icon NAME, or a raw emoji/initial string), an optional muted secondary line, an
 * optional right-aligned mono meta, and an optional per-item disabled flag.
 */
export interface AuComboboxOption {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Stable value the consumer maps back to on `au-change` and matches against the combobox value. */
  value: string
  /** The option label, shown in the row and (single-select) echoed in the field. */
  label: string
  /**
   * Optional leading glyph: an au-icon NAME (e.g. `file-text`) rendered as an icon, else a raw string
   * (an emoji flag, an initial) rendered verbatim.
   */
  icon?: string
  /** Optional muted second line (email / role / path) — makes a two-line row. */
  secondary?: string
  /** Optional right-aligned mono meta (dial code / count / shortcut). */
  meta?: string
  /** Disable just this option (it stays visible but is not selectable). */
  disabled?: boolean
}

/**
 * One command-palette row: id (keys the action), label (matched + shown), optional icon (au-icon glyph
 * name), a keymap shortcut (rendered as an au-kbd cluster), a secondary detail line, a group label
 * (clusters rows under a section header), and a danger flag (a destructive verb, danger ink under the cursor).
 */
export interface AuCommandItem {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Stable id the consumer maps back to an action on `au-run` (e.g. a file path). */
  id: string
  /** The text shown + fuzzy-matched against the query; the typed run is raised by ink weight. */
  label: string
  /** Optional secondary text (e.g. the full path under a basename). */
  detail?: string
  /** Optional leading glyph — an au-icon name (so rows align). */
  icon?: string
  /** Optional keymap string (`Mod-P`) rendered as a trailing au-kbd cluster. */
  shortcut?: string
  /** Optional group label — rows sharing one cluster under a section header (grouped variant). */
  group?: string
  /** Marks a destructive verb — danger ink shows only when the row is the active cursor. */
  danger?: boolean
}

/**
 * <au-command-palette> — a ⌘K launcher: pass `items`, the element filters + navigates + emits au-run
 * with the chosen id. `grouped` (default) shows section headers + icons + shortcut clusters + a footer
 * legend; `compact` is the flat dense picker. Selection is a soft wash + ink raise, never a bright fill.
 * Uses shared picker entrance motion. A consumer sets data-state="closed", makes the surface inert,
 * and retains it through its finite exit animations before removal. Reduced motion settles immediately.
 */
export interface AuCommandPalette extends Omit<UiComponent, 'type'> {
  type: 'au-command-palette'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The rows to search. Set as a PROPERTY (complex data), not an attribute. Render-resilient: empty. */
  items?: AuCommandItem[]
  /** grouped (default) — section headers + shortcut clusters + footer legend; compact — flat dense list. */
  variant?: 'grouped' | 'compact'
  /** Input placeholder. */
  placeholder?: string
  /** Swap the leading search glyph for a spinner while results load. */
  loading?: boolean
}

/**
 * One <au-detail-list> row: a term (the muted key), an optional value (the bright datum), a `mono`
 * flag for identifier values (ids / paths / sizes / timestamps on tabular figures), and an optional
 * status `tone` that tints the value TEXT (never a rail). A null / empty value renders a faint
 * em-dash, never blank.
 */
export interface AuDetailItem {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The key — the muted half of the two ink steps. */
  term: string
  /** The datum. Null / empty renders a faint em-dash. */
  value?: string
  /** Render the value in Geist Mono on tabular figures (ids / paths / sizes / durations / timestamps). */
  mono?: boolean
  /** The status tone for the value — ok / warn / danger. Drives tinted text, or the dot / badge fill. */
  tone?: 'ok' | 'warn' | 'danger'
  /**
   * How the value reads. `text` (default) tints the value TEXT; `dot` composes an au-status-dot before
   * neutral text; `badge` renders the value as a filled au-badge pill.
   */
  valueKind?: 'text' | 'dot' | 'badge'
}

/**
 * <au-detail-list> — the key/value property list for inspector + detail/peek panes (the "file-peek"
 * pattern). DATA-DRIVEN: `items` is a au-detail-item[] the consumer owns. The whole hierarchy rides two
 * ink steps — a muted term, a bright value — with Geist Mono for identifier values on tabular figures.
 * Status is tinted value TEXT only (never a rail). Two layouts: `inline` (term left / value right) and
 * `stacked` (micro-cap term above the value). Non-interactive.
 */
export interface AuDetailList extends Omit<UiComponent, 'type'> {
  type: 'au-detail-list'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The rows. The consumer owns them; the list renders term/value pairs. */
  items?: AuDetailItem[]
  /** inline = term left / value right on one baseline; stacked = micro-cap term above the value. */
  layout?: 'inline' | 'stacked'
  /** Draw an opt-in hairline between adjacent rows. Off by default — whitespace does the grouping. */
  separators?: boolean
}

/**
 * <au-diff-line> — one line of a code diff (add | del | context): a faint whole-line tint + a +/− gutter
 * glyph in the tone colour, never an edge bar. Composed inside <au-code-block>. Code text is the default slot.
 */
export interface AuDiffLine extends Omit<UiComponent, 'type'> {
  type: 'au-diff-line'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Diff kind — add (tinted ok), del (tinted danger), or context (bare). */
  kind?: 'context' | 'add' | 'del'
  /** Old-file line number (blank on an added line). */
  oldNo?: string
  /** New-file line number (blank on a removed line). */
  newNo?: string
}

/**
 * <au-divider> — a 1px hairline rule, horizontal or vertical. `weight` picks subtle/default/strong;
 * `inset` insets the rule from its container edges.
 */
export interface AuDivider extends Omit<UiComponent, 'type'> {
  type: 'au-divider'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Rule axis. Vertical stretches to its flex parent's cross-size. */
  orientation?: 'horizontal' | 'vertical'
  /** Hairline weight: subtle = line-1, default = line-2, strong = line-3. */
  weight?: 'default' | 'subtle' | 'strong'
  /** Inset the rule from its container edges. */
  inset?: boolean
}

/**
 * The interface for <au-drawer>: an edge-anchored slide-in sheet (au-modal's docked sibling). `side`
 * right/left/bottom, `size` sm/md/lg, `posture` modal (scrim+elev-5) or flush (elev-3, no scrim).
 * heading + subtitle, slots for header-actions / body (default) / footer, optional × + resize seam.
 * Look-only (claims no overlay). Emits `au-close`.
 */
export interface AuDrawer extends Omit<UiComponent, 'type'> {
  type: 'au-drawer'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Whether the drawer is slid in. Reflected — the consumer toggles it; the panel animates both ways. */
  open?: boolean
  /** The docking edge + slide axis. `right` (default), `left` (mirrors right), `bottom` (full-width sheet). */
  side?: 'right' | 'left' | 'bottom'
  /** Panel width (right/left) / capped height (bottom): sm/md/lg = 320/400/480. */
  size?: 'sm' | 'md' | 'lg'
  /** `modal` (default — scrim + elev-5 + glass) or `flush` (elev-3, no scrim, the page stays interactive). */
  posture?: 'modal' | 'flush'
  /** The panel heading (the accessible name). */
  heading?: string
  /** A muted second line under the heading. */
  subtitle?: string
  /** Show a top-right × close (emits `au-close`). */
  dismissible?: boolean
  /**
   * Render a presentational resize seam on the docking edge (a grabber for `side=bottom`). The
   * container owns the drag physics.
   */
  resizable?: boolean
}

/**
 * <au-drop-zone> — the pane-drag landing indicator. An absolute, display-only overlay (aria-hidden,
 * pointer-events:none) docked over the receiving slot: a hairline receiver frame + a directional
 * ink-wash band that slides between the five zones (top/right/bottom/left/center) on the transport
 * ease. Direction lives in the band's position + sheen, never a colored bar. Mirrors the container
 * substrate's DropZone vocabulary. Drive `zone` as the drag moves; clearing `zone` fades the band
 * while it holds its last geometry. The default slot overrides the action caption with source and
 * destination identity. Captions use compact sans UI type and small rounded corners. The caption sits inside the landing band, truncates within its bounds, and hides in very narrow bands.
 */
export interface AuDropZone extends Omit<UiComponent, 'type'> {
  type: 'au-drop-zone'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The landing zone the band highlights. Absent = a drag is in flight but the cursor sits between zones (band holds + fades). */
  zone?: 'center' | 'top' | 'right' | 'bottom' | 'left'
  /** A drag is in flight. False removes the overlay entirely. Default true. */
  active?: boolean
  /** Show the action label chip ("Split up" / "Add tab" …). Default true. */
  label?: boolean
  /** Edge-band thickness as a fraction of the slot (center is always the middle 50% box). Default 0.25. */
  edgeRatio?: number
  /** Corner radius of the overlay, matching the host slot. A CSS length or var(). Default var(--au-radius-md). */
  radius?: string
}

/**
 * <au-empty-state> — centered empty-slot messaging: `label` + optional `hint` (string props), with
 * optional `icon` / `action` slots. `title` is renamed `label` — a `title` prop shadows the native tooltip.
 */
export interface AuEmptyState extends Omit<UiComponent, 'type'> {
  type: 'au-empty-state'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The heading line. */
  label?: string
  /** An optional secondary line. */
  hint?: string
}

/**
 * The interface for <au-field>: the form-row composition primitive. Wraps a control (default slot)
 * with a label, optional hint, and an `error` danger-ink message. stack = label above, inline = grid.
 */
export interface AuField extends Omit<UiComponent, 'type'> {
  type: 'au-field'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Simple label text (slot fallback). For rich label content, slot into `label` instead. */
  label?: string
  /** Helper text below the control (shown unless `error` replaces it). */
  hint?: string
  /**
   * When set, replaces the hint with a danger-ink message. (The slotted control carries its own
   * error state; au-field does not reach across the shadow boundary to set it.)
   */
  error?: string
  /** Draw a subtle required marker after the label. */
  required?: boolean
  /** stack = label above the control; inline = a two-column grid (label · control). Default stack. */
  layout?: 'stack' | 'inline'
}

/**
 * The interface for <au-grip-glyph>: the drag-handle affordance on a pane / tab / region label bar.
 * Stateless — the container wires the pointer drag. Decorative (aria-hidden) unless given a `label`.
 */
export interface AuGripGlyph extends Omit<UiComponent, 'type'> {
  type: 'au-grip-glyph'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The in-flight drag state — locked/grabbing visuals. The container sets this while a drag is active. */
  dragging?: boolean
  /** De-emphasized; suppresses click and keyboard activation and removes named grips from the tab order. */
  disabled?: boolean
  /** Accessible name. Absent or blank → decorative; nonblank → focusable button. Click, Enter and Space activate the consumer-owned action; the container supplies drag and move options. */
  label?: string
}

/**
 * <au-hovercard> — the peek shell for cmd-hover previews: a raised surface (surface-1 + hairline + pop
 * shadow, panel radius) with a soft projected-out pop-in. `origin` sets where the pop-in emanates FROM
 * so it grows out of the anchor. LOOK ONLY — the host preview overlay owns positioning + the claim;
 * content is the default slot.
 */
export interface AuHovercard extends Omit<UiComponent, 'type'> {
  type: 'au-hovercard'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Where the pop-in emanates FROM (the transform-origin), so it grows out of the anchor side. */
  origin?: 'top-center' | 'bottom-center' | 'top-left' | 'bottom-left' | 'center'
}

/**
 * The interface for <au-icon>: a type-scaled inline-SVG glyph. `name` picks the shape; it scales
 * with the type ramp and inherits `currentColor`. Decorative by default; `label` makes it labelled.
 */
export interface AuIcon extends Omit<UiComponent, 'type'> {
  type: 'au-icon'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Glyph name (e.g. `gear`, `search`, `chevron-right`). The set owns the shape table. */
  name: string
  /** Size step, bound to the type ramp (--au-t-*). Default md. */
  size?: 'xs' | 'sm' | 'md' | 'lg'
  /** Accessible name. Omitted, empty or whitespace-only → decorative (aria-hidden); a non-empty trimmed label → role=img + <title>. */
  label?: string
}

/**
 * The interface for <au-icon-button>: a square button whose visible label is a slotted glyph.
 * `label` is the accessible name (required in practice). Emits `au-activate` on press.
 */
export interface AuIconButton extends Omit<UiComponent, 'type'> {
  type: 'au-icon-button'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Accessible name — the visible label is a glyph, so a name is required for a11y. */
  label: string
  /** Square side step. xs/sm/md/lg = 6/7/8/10 spacing units (24/28/32/40px at base density); sm/md/lg share <au-button>'s metrics. Default md. */
  size?: 'xs' | 'sm' | 'md' | 'lg'
  /** Hover treatment. `chrome` (shared chrome hover wash) or `panel` (surface fill, for raised panels). Default chrome. */
  surface?: 'chrome' | 'panel'
  /** Non-interactive + de-emphasized. Also reflected as the `disabled` state; suppresses activation. */
  disabled?: boolean
}

/**
 * The interface for <au-input>: a single-line text field. Form-associated (its value joins a native
 * form); error paints the danger ring; borderless strips its chrome for a composing frame.
 */
export interface AuInput extends Omit<UiComponent, 'type'> {
  type: 'au-input'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The field's value (form-associated: participates in a native form + reset). */
  value?: string
  /** Placeholder text shown when empty. */
  placeholder?: string
  /** The native input type (text / password / email / number / …). Default text. (Not `type` — reserved.) */
  inputType?: string
  /** Size step. sm/md/lg = 28/32/40, parity with au-button. Default md. */
  size?: 'sm' | 'md' | 'lg'
  /** Non-interactive + de-emphasized. Reflected as the `disabled` state. */
  disabled?: boolean
  /** Paint the error border + focus ring (danger) and set aria-invalid. Reflected as `error`. */
  error?: boolean
  /**
   * Strip the field's own chrome (border/fill/radius/ring) for a field inside a frame that draws the
   * boundary — a combobox popover, a command-palette card. The frame + caret carry focus.
   */
  borderless?: boolean
  /** Native spellcheck on the inner field. Defaults on; set off for a filename / pattern / code field. */
  spellcheck?: boolean
}

/**
 * <au-kbd> — a keyboard-shortcut chip. Pass a keymap string via `keys` (`Mod-Shift-o`) — formatted
 * through the shortcut resolver (`Mod` → ⌘ on macOS, Ctrl elsewhere) — or slot literal content. A mono
 * glyph on the base surface tone with a soft inset hairline. Formatted keys have a space-0-5 gap
 * between segments; literal slotted content keeps its own spacing. Non-interactive.
 */
export interface AuKbd extends Omit<UiComponent, 'type'> {
  type: 'au-kbd'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** A keymap string (`Mod-Shift-o`), rendered as formatted keystroke glyphs. Omit to slot literal content. */
  keys?: string
  /** Force macOS glyphs (⌘ / ⌥). Defaults to platform detection. */
  mac?: boolean
}

/**
 * <au-list-row> — the generic dense row: an optional `leading` slot, a `primary` label + optional
 * `secondary` line, an optional `meta` slot, an optional `trailing` slot. `interactive` opts into the
 * hover-lift + focus ring; `selected` rests on a surface tint. Emphasis is surface + ink, never a rail.
 */
export interface AuListRow extends Omit<UiComponent, 'type'> {
  type: 'au-list-row'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Wrap primary and secondary text without truncation. Keep long context in secondary; meta is for compact values. */
  wrap?: boolean
  /** The primary label (ellipsised on overflow). */
  primary?: string
  /** An optional secondary line under the primary. */
  secondary?: string
  /** Opt into hover / focus affordances + keyboard focusability. */
  interactive?: boolean
  /** Resting selected state — a surface lift (never a leading bar). */
  selected?: boolean
  /** Dim + non-interactive. */
  disabled?: boolean
}

/**
 * <au-menu> — a floating menu surface (the DropdownMenu look): elev-5 fill + inset hairline + glass
 * shadow, panel radius, a small pad. A padded list of <au-menu-item> rows (+ <au-divider> separators /
 * section labels) slotted in. The LOOK only — a host surface (context-menu / chooser) owns positioning,
 * keyboard nav, and submenus.
 */
export interface AuMenu extends Omit<UiComponent, 'type'> {
  type: 'au-menu'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

/**
 * <au-menu-item> — one menu row. A label (+ optional icon / trailing shortcut / a second muted
 * description line), highlighted by a translucent wash (accent-soft on hover, selection-bg when active)
 * that LIFTS on any card elevation — never a solid surface fill. active / disabled / destructive states;
 * an optional trailing submenu chevron. Emits au-activate on click (unless disabled).
 */
export interface AuMenuItem extends Omit<UiComponent, 'type'> {
  type: 'au-menu-item'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The row label. */
  label?: string
  /** An optional second, muted line (a chooser / palette row description). */
  description?: string
  /** A leading au-icon glyph name. */
  icon?: string
  /** Trailing mono shortcut text (e.g. ⌘K). */
  shortcut?: string
  /** Keyboard/hover highlight — the firmer selection wash (for the arrow-keyed / hovered row). */
  active?: boolean
  /** Non-interactive + de-emphasized. */
  disabled?: boolean
  /** A destructive action — danger ink. */
  destructive?: boolean
  /** Show a trailing submenu chevron. */
  submenu?: boolean
}

/**
 * <au-meter> — a determinate progress / ratio bar. A rounded track (surface-3 + an inset hairline)
 * with an ink FILL sized by `value` (0..1). Monochrome by default — progress is a weight, not a
 * colour; a `tone` re-tints the fill to a status hue via color-mix (the au-status-dot technique),
 * staying in the palette family. A horizontal bar, never a left-edge accent rail. `indeterminate`
 * rides a token-eased sliding segment (static under reduced motion). Optional label + value read-out.
 */
export interface AuMeter extends Omit<UiComponent, 'type'> {
  type: 'au-meter'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Progress ratio 0..1 (clamped). Ignored when `indeterminate`. */
  value?: number
  /** An optional caption above the track (sans, muted). */
  label?: string
  /** An optional read-out above the track, right-aligned (mono, tabular). e.g. "3/6" or "50%". */
  valueLabel?: string
  /** Re-tint the fill to a status hue via color-mix; absent is monochrome ink. */
  tone?: 'ok' | 'warn' | 'danger'
  /** Unknown progress — a sliding segment (collapses to static under reduced motion). */
  indeterminate?: boolean
}

/**
 * <au-modal> — the anchor of the overlay elevation family: a dialog card. Elev-5 fill + inset hairline
 * + glass shadow, panel radius. A heading, a body (default slot), and an optional actions shelf (the
 * `actions` slot — a hairline-topped same-surface footer) that appears only when filled. An optional top-right
 * × close (emits au-close). NEVER a leading/left accent bar. The LOOK only — a host surface owns the
 * scrim, focus-trap, and lifecycle.
 */
export interface AuModal extends Omit<UiComponent, 'type'> {
  type: 'au-modal'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The dialog title (`title` is the reserved native tooltip, so this is `heading`). */
  heading?: string
  /** Elevation variant: default (panel radius + glass shadow) or preview (softer peek surface). */
  variant?: 'default' | 'preview'
  /** Show a top-right × close (emits au-close). */
  dismissible?: boolean
}

/**
 * The interface for <au-nav-group>: a titled row cluster. `label` eyebrow + `count`, default-slot
 * rows, `actions` slot; `collapsible` / `open` / `sans` / `caps`. Emits au-toggle.
 */
export interface AuNavGroup extends Omit<UiComponent, 'type'> {
  type: 'au-nav-group'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The eyebrow text. */
  label?: string
  /** A right-aligned trailing count on the eyebrow. */
  count?: string
  /** Make the eyebrow a disclosure control; when collapsed the items slot is not rendered. */
  collapsible?: boolean
  /** Disclosure state. Default false (closed); a non-collapsible group always shows its items. */
  open?: boolean
  /** Step the eyebrow up to the full sans reading face (a named panel section). */
  sans?: boolean
  /** Opt the eyebrow into the mono UPPERCASE face. */
  caps?: boolean
  /** Put the eyebrow's disclosure chevron at the TRAILING (right) edge instead of leading. */
  chevronEnd?: boolean
}

/**
 * The interface for <au-nav-item>: a nav-list row. Leading `icon` slot + default-slot label +
 * `trailing` slot; `selected` firms it to the current row. Emits au-activate on press.
 */
export interface AuNavItem extends Omit<UiComponent, 'type'> {
  type: 'au-nav-item'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The current / active row — firms to surface-2 + a hairline ring, sets aria-current=page. */
  selected?: boolean
  /** Non-interactive + de-emphasized. Reflected as the `disabled` state; suppresses activation. */
  disabled?: boolean
}

/**
 * Text-role fallbacks match the base ink palette without token stylesheets.
 * The interface for <au-number-input>: a numeric spinbutton — stepper / scrub / split variants, tabular
 * mono digits, keyboard + wheel + hold-repeat + drag-scrub, clamp/round. Form-associated. `value` is a
 * Number, empty is null. Emits `au-input` / `au-change {value}`.
 */
export interface AuNumberInput extends Omit<UiComponent, 'type'> {
  type: 'au-number-input'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The numeric value. Empty is null (the placeholder shows). Form-associated. */
  value?: number
  /** Lower bound. Home jumps to it; steps clamp to it (unless `wrap`). */
  min?: number
  /** Upper bound. End jumps to it; steps clamp to it (unless `wrap`). */
  max?: number
  /** Base increment for arrows / carets / wheel. Default 1. */
  step?: number
  /** Shift+Arrow · PageUp/Down · Shift-scrub increment. Default `step * 10`. */
  largeStep?: number
  /** Alt/Option-scrub fine increment. Default `step / 10`. */
  fineStep?: number
  /** Decimals to round to on commit. Default inferred from `step`. */
  precision?: number
  /** Wrap max → min (cyclic values like degrees). */
  wrap?: boolean
  /** Muted mono suffix folded into `aria-valuetext` — 'px' | '%' | '°' | 'ms' | … */
  unit?: string
  /** Leading label / glyph prefix; the drag handle in the `scrub` variant (a short string or au-icon name). */
  leading?: string
  /** Affordance shape. `stepper` (default, trailing carets), `scrub` (hover-in column), `split` (− value +). */
  variant?: 'stepper' | 'scrub' | 'split'
  /** Value alignment. `left` (forms, default) or `right` (property grids). */
  align?: 'left' | 'right'
  /** Height step. `md` (default), `sm`, `lg` — parity with au-input. */
  size?: 'sm' | 'md' | 'lg'
  /** Enable drag-scrub on the leading label. Default true in `scrub`, else false. */
  scrubbable?: boolean
  /** Async value pending — a spinner rides the trailing slot and the value dims. */
  loading?: boolean
  /** Paints the danger border + ring and sets aria-invalid. Reflected as the `error` state. */
  error?: boolean
  /** Placeholder shown when the value is null. */
  placeholder?: string
  /** Non-interactive + de-emphasized. Reflected as the `disabled` state. */
  disabled?: boolean
  /** Read-only — the value shows but cannot be edited or stepped. */
  readonly?: boolean
  /** Accessible name for the spinbutton. */
  label?: string
}

/**
 * The interface for <au-output-log>: a scrolling monospace log tail. `lines` (a String[] property,
 * newest last) capped at `maxLines`; auto-follows the tail unless scrolled up. Composes au-scroll-area.
 * A read-only surface — no events.
 */
export interface AuOutputLog extends Omit<UiComponent, 'type'> {
  type: 'au-output-log'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The log lines, one entry per line, newest LAST. Set as a PROPERTY (an array), not an attribute. */
  lines?: string[]
  /** Keep at most this many lines; oldest beyond it drop off the top. Default 500. */
  maxLines?: number
}

/**
 * The interface for <au-pagination>: a controlled table/list footer — a range/count summary, a
 * windowed pager (prev/next + numbered cells with `…`, or a Page X of Y chip), and an optional
 * rows-per-page au-select. Variants numbered / cursor / compact; sizes comfortable / dense. Emits
 * `au-page-change {page}` + `au-page-size-change {size}`.
 */
export interface AuPagination extends Omit<UiComponent, 'type'> {
  type: 'au-pagination'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The 1-based current page. */
  page?: number
  /** Total number of pages. */
  pageCount?: number
  /** `numbered` (default) — page cells + `…`; `cursor` — a Page X of Y chip; `compact` — tight, right-aligned. */
  variant?: 'numbered' | 'cursor' | 'compact'
  /** Bar height. `comfortable` (40) or `dense` (32). */
  size?: 'comfortable' | 'dense'
  /** Total row count — enables the left summary. Absent → no summary. */
  total?: number
  /** The summary form: `range` (needs pageSize) or `count`. Default range when pageSize is set, else count. */
  summary?: 'range' | 'count'
  /** Rows per page — enables the right-hand rows-per-page au-select. */
  pageSize?: number
  /** The offered page sizes. Default [10, 20, 50, 100]. */
  pageSizeOptions?: number[]
  /** Numbered variant — pages either side of the current cell. Default 1. */
  siblingCount?: number
  /** Numbered variant — pages pinned at each end. Default 1. */
  boundaryCount?: number
  /** Show the «/» first / last jump (numbered / cursor). Default false. */
  showFirstLast?: boolean
  /** Swap the summary + page cells for skeletons while a page fetches; the bar height stays frozen. */
  loading?: boolean
  /** Accessible name for the pager nav. */
  label?: string
}

/**
 * The interface for <au-pane-frame>: the bordered / rounded / elevated card a projection mounts inside,
 * with an optional sticky label bar (leading · title · meta, or a `label` slot that replaces them).
 */
export interface AuPaneFrame extends Omit<UiComponent, 'type'> {
  type: 'au-pane-frame'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The active pane — lifts the card ring to full ink emphasis. */
  focused?: boolean
  /** A danger hairline on the whole card. */
  error?: boolean
  /** A transient (preview) pane — italicises the title ONLY, never a different card treatment. */
  preview?: boolean
  /** Drop the body padding, for a projection that owns its own insets. */
  flush?: boolean
  /** Surround a nested container with an even gutter; clicking that gutter pins its compact header open; hover only identifies the frame. */
  nested?: boolean
  /** Keep the nesting header revealed while its menu or inline picker is in use. */
  engaged?: boolean
}

/**
 * The interface for <au-pane-header>: the single masthead row a container composes — grip · title ·
 * optional divider · center slot · actions. `surface` panel (card) or rail (chrome). Direct occupants may share its center; distinct nested scopes can retain separate rows.
 */
export interface AuPaneHeader extends Omit<UiComponent, 'type'> {
  type: 'au-pane-header'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Wrapper header expands when its frame is pinned open or its controls receive keyboard focus; the enclosing nested pane-frame supplies equal insets. Rail headers remain compact rows. Default false. */
  compact?: boolean
  /** Name of the container enclosed by this frame. Reveals above contributed tabs; group controls remain directly accessible in the shared row. Never names the parent providing the header. */
  context?: string
  /** `panel` names a card masthead; `rail` names shell chrome. Both use shared row geometry; the enclosing frame owns boundaries. Default panel. */
  surface?: 'panel' | 'rail'
  /** Pane focus context; individual controls own keyboard focus and the enclosing frame owns the main focus boundary. */
  focused?: boolean
  /** Draw the vertical hairline between the fixed title and the center slot. */
  divider?: boolean
  /** Render a default drag handle (<au-grip-glyph>) in the leading region when no `leading` slot is given. */
  draggable?: boolean
}

/**
 * <au-pane-target> — a pane offered as a SELECTION target, the interactive sibling of <au-drop-zone>.
 * An absolute overlay docked over a candidate pane's rect: a receiver frame (the drop-zone's hairline +
 * soft ink fill vocabulary) with a resting and a highlighted (`active`) state, an optional keyboard letter
 * HINT (an <au-kbd> keycap, top-left) and an optional caption LABEL (a mono chip, centered). Unlike the
 * drop-zone it is INTERACTIVE — hover lifts the frame, a click emits `au-activate`. The spatial
 * presentation of the host chooser's CHOOSE strategy (dock "into which container?", and any ambiguous
 * ambient intent). Positioned by the host from a live getBoundingClientRect.
 */
export interface AuPaneTarget extends Omit<UiComponent, 'type'> {
  type: 'au-pane-target'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Highlighted (the keyboard/arrow-nav selection). Reflected. Default false. */
  active?: boolean
  /** The keyboard letter-hint shown as an <au-kbd> keycap, top-left. Absent = no hint. */
  hint?: string
  /** An optional caption naming what picking does (e.g. the container name), a mono chip centered over the pane. */
  label?: string
  /** Non-selectable (dimmed, pointer-events off). Reflected. Default false. */
  disabled?: boolean
}

/**
 * <au-pill> — a read-only status or metadata label with an optional decorative dot and theme-derived tone.
 * Content remains readable at narrow widths. Draft emphasizes, muted recedes, and pulse marks activity unless reduced motion is requested.
 */
export interface AuPill extends Omit<UiComponent, 'type'> {
  type: 'au-pill'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Show a leading status dot. */
  dot?: boolean
  /** Draft emphasis — brightens the dot + text. */
  draft?: boolean
  /** Recede the text one ink step. */
  muted?: boolean
  /** Optional semantic or accent tint; the label must communicate the state independently of color. */
  tone?: 'neutral' | 'accent' | 'ok' | 'warn' | 'danger'
  /** Gently pulse the visible dot for an active state. Muted and reduced-motion states remain static. */
  pulse?: boolean
}

/**
 * <au-popover> — a floating panel of the overlay elevation family: elev-5 fill + inset hairline + glass
 * shadow, panel radius, an optional directional arrow per `side`, an optional heading, and a body slot.
 * LOOK ONLY — a host/consumer surface mounts it into a claimed host.overlay layer and anchors it (the
 * au-modal split); it owns no positioning or dismissal. A consumer drives the exit via data-state="closed".
 */
export interface AuPopover extends Omit<UiComponent, 'type'> {
  type: 'au-popover'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The side the panel points FROM — drives the arrow position. */
  side?: 'top' | 'right' | 'bottom' | 'left'
  /** Whether to show the directional arrow (a rotated fill square). On by default. */
  arrow?: boolean
  /** An optional title line above the body. */
  heading?: string
  /** Own one bounded scroll body; heading and footer remain outside scrolling. */
  scrollable?: boolean
}

/**
 * The interface for <au-radio-group>: a vertical single-select group over `items` (au-radio-item[]) —
 * token ring + ink-1 dot rows. Form-associated. Emits `au-change {value}`. Roving tabindex + Arrow keys.
 */
export interface AuRadioGroup extends Omit<UiComponent, 'type'> {
  type: 'au-radio-group'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The option model. The consumer owns it; the control renders + navigates. */
  items?: AuRadioItem[]
  /** The selected option's value. Form-associated (participates in a native form + reset). */
  value?: string
  /** Disable the whole group (a per-item `disabled` can also disable one option). Reflected as `disabled`. */
  disabled?: boolean
  /** Accessible name for the radiogroup. */
  label?: string
}

/**
 * One <au-radio-group> option: value (keys select + matches against the group value), label, and an
 * optional per-item disabled flag.
 */
export interface AuRadioItem {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Stable value the consumer maps back to on `au-change` and matches against the group `value`. */
  value: string
  /** The option label, shown beside its ring. */
  label: string
  /** Disable just this option (the group can also disable every option at once). */
  disabled?: boolean
}

/**
 * <au-scroll-area> — the scrolling surface primitive: hairline tokened scrollbars, no chunky OS default.
 * Takes no size of its own — constrain it via style/parent. `axis` clamps the direction. Default slot.
 */
export interface AuScrollArea extends Omit<UiComponent, 'type'> {
  type: 'au-scroll-area'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Flow content normally, or center one content block in the available body. Oversized centered content stays reachable from the scroll start. */
  content?: 'flow' | 'center'
  /** Which axes may scroll: both (default), x (horizontal only), or y (vertical only). */
  axis?: 'both' | 'x' | 'y'
}

/**
 * The interface for <au-section-header>: a group-label eyebrow. Default-slot label + `count` +
 * `actions` slot; `collapsible` / `open` / `sans` / `caps` / `locked`. Emits au-toggle.
 */
export interface AuSectionHeader extends Omit<UiComponent, 'type'> {
  type: 'au-section-header'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** A right-aligned trailing count (a machine-ish number, pinned to the quiet mono face). */
  count?: string
  /** Make the header a disclosure control — composes a leading chevron, emits au-toggle on activate. */
  collapsible?: boolean
  /** Disclosure state (rotates the chevron). Default false (closed); a non-collapsible header ignores it. */
  open?: boolean
  /** Step the label up to the full sans reading face for a NAMED panel section. */
  sans?: boolean
  /** Opt into the mono UPPERCASE eyebrow — reserve for a genuinely machine-ish (status / enum) label. */
  caps?: boolean
  /** Put the disclosure chevron at the TRAILING (right) edge instead of leading. */
  chevronEnd?: boolean
  /** Structure-locked group — the label reads a step quieter and collapse is suppressed. */
  locked?: boolean
}

/** One <au-segmented-control> segment: value (keys select), label, and an optional au-icon glyph name. */
export interface AuSegmentItem {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Stable value the consumer maps back to on `au-change` and matches against `value`. */
  value: string
  /** The segment label. */
  label: string
  /** Optional leading au-icon glyph NAME (a string, not a framework node). */
  icon?: string
}

/**
 * The interface for <au-segmented-control>: a pill-in-tray toggle over `items` (au-segment-item[]).
 * Emits `au-change {value}`. Roving tabindex + Arrow/Home/End keyboard nav.
 */
export interface AuSegmentedControl extends Omit<UiComponent, 'type'> {
  type: 'au-segmented-control'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The segment model. The consumer owns it; the control renders + navigates. */
  items?: AuSegmentItem[]
  /** The selected segment's value. */
  value?: string
  /** Non-interactive + de-emphasized. Reflected as the `disabled` state. */
  disabled?: boolean
  /** Accessible name for the choice group. */
  label?: string
}

/**
 * The interface for <au-select>: a value-picker — a field trigger + a floating listbox over `options`
 * (au-select-option[]) drawn through host.overlay. Form-associated. Emits `au-change {value}`. Keyboard
 * listbox nav (Arrow/Home/End/Enter/Escape).
 */
export interface AuSelect extends Omit<UiComponent, 'type'> {
  type: 'au-select'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The option model. The consumer owns it; the control renders + navigates. */
  options?: AuSelectOption[]
  /** The chosen option's value. Empty → the placeholder shows. Form-associated. */
  value?: string
  /** Shown in the field when nothing is selected. */
  placeholder?: string
  /** Non-interactive + de-emphasized. Reflected as the `disabled` state. */
  disabled?: boolean
  /** Trigger height step. `md` (default), `sm` (dense rows), `lg` (roomy) — parity with au-input. */
  size?: 'sm' | 'md' | 'lg'
  /** Accessible name for the trigger + listbox. */
  label?: string
  /** Optional icon-only trigger; label supplies its accessible name. */
  triggerIcon?: string
}

/**
 * One <au-select> option: value (keys select + matches against the field value), label, an optional
 * leading au-icon glyph name, and an optional per-item disabled flag.
 */
export interface AuSelectOption {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Stable value the consumer maps back to on `au-change` and matches against the select `value`. */
  value: string
  /** The option label, shown in the row and (when chosen) echoed in the field. */
  label: string
  /** Optional leading au-icon glyph NAME (a string, not a framework node), shown in the row + field. */
  icon?: string
  /** Disable just this option (it stays visible but is not selectable). */
  disabled?: boolean
}

/** Responsive settings group with explanatory introduction and slotted controls. Presentation only; owns no values, validation or save behavior. */
export interface AuSettingsSection extends Omit<UiComponent, 'type'> {
  type: 'au-settings-section'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  heading?: string
  description?: string
  compact?: boolean
}

/**
 * The interface for <au-skeleton>: the calm loading placeholder (the silhouette of content coming).
 * Neutral ink-channel bars (never hued, never a leading accent bar) carrying one shared shimmer sweep.
 * variant text / block / rect / circle. `label` makes it an accessible loading region.
 */
export interface AuSkeleton extends Omit<UiComponent, 'type'> {
  type: 'au-skeleton'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Shape mirrored from the real content: text (pill line), block/rect (media box), circle (avatar/dot). */
  variant?: 'text' | 'block' | 'rect' | 'circle'
  /** CSS length or % sizing the bar (text) or box; also the diameter of a circle. A number is px. */
  width?: string
  /** CSS length for a box height; ignored for text; a circle mirrors width. A number is px. */
  height?: string
  /** text only — number of stacked line-bars; the last is auto-ragged so text reads unevenly. */
  lines?: number
  /** Corner radius token for block/rect (default chip). Ignored for text (pill) and circle (pill). */
  radius?: 'pill' | 'panel' | 'row' | 'chip' | 'sm' | 'md' | 'none'
  /** When set, the root becomes an accessible loading region (role=status + aria-busy) announcing this. */
  label?: string
}

/**
 * Ink-role fallbacks match the base palette without token stylesheets.
 * The interface for <au-slider>: a native <input type=range>, token-painted — a thin track, an ink-2
 * fill on the traversed portion, a lifted thumb (scale cue, never a hue). Form-associated. Emits
 * `au-input` (live) + `au-change` (commit). `label` is the accessible name.
 */
export interface AuSlider extends Omit<UiComponent, 'type'> {
  type: 'au-slider'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The current value. */
  value?: number
  /** Range minimum. */
  min?: number
  /** Range maximum. */
  max?: number
  /** Step increment. */
  step?: number
  /** Non-interactive + dimmed. Reflected as the `disabled` state. */
  disabled?: boolean
  /** Accessible name for the slider. */
  label?: string
}

/**
 * <au-spinner> — an indeterminate activity ring. `size` sm/md/lg; `label` names it for assistive tech.
 * Collapses to a static neutral ring under reduced motion.
 */
export interface AuSpinner extends Omit<UiComponent, 'type'> {
  type: 'au-spinner'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Size step. Default md. */
  size?: 'md' | 'sm' | 'lg'
  /** Accessible name (role=status). Default "Loading". */
  label?: string
}

/**
 * Hairline knob is a rounded notch shown on hover/focus/drag; the hit target remains available at rest.
 * The interface for <au-splitter>: the sash LOOK between two panes. A transparent grab strip with a
 * centered hairline + optional knob that lift to the accent on hover / drag. The container owns physics.
 */
export interface AuSplitter extends Omit<UiComponent, 'type'> {
  type: 'au-splitter'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Vertical (between side-by-side panes, col-resize) or horizontal (stacked, row-resize). Default vertical. */
  orientation?: 'vertical' | 'horizontal'
  /** The in-flight resize — lifts the hairline + knob to the accent. The container sets this while dragging. */
  dragging?: boolean
  /** Non-resizable seam — faint hairline, no knob, no resize cursor. */
  disabled?: boolean
  /** Show the small centered knob (a grab affordance). Default true. */
  knob?: boolean
  /** Draw the centered hairline. Default true; pass false when both neighbours already draw their own edge. */
  line?: boolean
  /** `hairline` (the mark) or `grab` (a touch-sized slab that overflows the seam). Default hairline. */
  knobSize?: 'hairline' | 'grab'
}

/**
 * The interface for <au-status-dot>: a small status dot. tone (ink/ok/warn/danger), variant (filled/ring),
 * an optional glow halo + pulse. Decorative by default; `label` names it when the dot IS the signal.
 */
export interface AuStatusDot extends Omit<UiComponent, 'type'> {
  type: 'au-status-dot'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /**
   * Colour role. `ink` (neutral, default), `ok` (positive/live), `warn` (transitional), `danger` (error/stopped).
   * The full status range so a status indicator (engine/mcp: ready/starting/stopped) reads without hand-rolling.
   */
  tone?: 'ink' | 'ok' | 'warn' | 'danger'
  /** `filled` solid dot (default) or `ring` hollow stale-indicator. */
  variant?: 'filled' | 'ring'
  /** Size step. Default md. */
  size?: 'sm' | 'md' | 'lg'
  /** Soft halo around the dot — the sync-pulse glow. */
  glow?: boolean
  /** Animate the glow as an expanding radar pulse (static under reduced motion). */
  pulse?: boolean
  /** Accessible name. Omitted → decorative (aria-hidden); present → role=img, the dot IS the signal. */
  label?: string
}

/**
 * One <au-stepper> step: a stable id, an optional label (omitted → a marker-only step), an optional
 * vertical-variant sub-label, an optional explicit state (derived from `current` when omitted), and a
 * `live` flag that rides a StatusDot-style pulse on the current step's marker.
 */
export interface AuStepItem {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Stable id the consumer maps back to on `au-step-select`. */
  id: string
  /** The step label. Omitted → a marker-only step (the dots posture even inside a labelled variant). */
  label?: string
  /** Vertical-variant helper line under the label (ink-4). */
  subLabel?: string
  /** Explicit visual state. Omitted → derived from `current` (< current → complete, = → current, > → upcoming). */
  state?: 'upcoming' | 'current' | 'complete' | 'disabled' | 'skipped' | 'error'
  /** The current step is doing live work → a StatusDot-style pulse ring rides its marker. */
  live?: boolean
}

/**
 * Text-role fallbacks match the base ink palette without token stylesheets.
 * The interface for <au-stepper>: ordered position in an N-step flow over `steps` (au-step-item[]),
 * `current` driving the ladder. Variants dots / horizontal / vertical; numbered markers; a chevron
 * or hairline separator; read-only / linear / free interaction. Emits `au-step-select {id, index}`.
 */
export interface AuStepper extends Omit<UiComponent, 'type'> {
  type: 'au-stepper'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The step model. The consumer owns it; the control renders + navigates. */
  steps?: AuStepItem[]
  /** The current step index (0-based); drives the derived complete / current / upcoming ladder. */
  current?: number
  /** Layout arrangement. */
  variant?: 'horizontal' | 'vertical' | 'dots'
  /** Markers carry mono numbers (→ a check on completion). Ignored by `dots`. */
  numbered?: boolean
  /** Horizontal only — a `›` glyph between steps instead of a hairline connector. */
  separator?: 'line' | 'chevron'
  /** Read-only (`none`), click-back-only (`linear`, completed steps), or jump-anywhere (`free`). */
  interactive?: 'none' | 'linear' | 'free'
  /** Render a mono `n/m` read-out after the steps. */
  countLabel?: boolean
  /** Accessible name for the flow. */
  label?: string
}

/**
 * <au-swatch> — a token-value colour chip. The FILL is the value being shown (the ONE place a colour
 * legitimately paints in chrome); a hairline ring keeps a pale swatch edged on a pale surface, and
 * `alpha0` reveals a checker so a transparent value reads as no-paint. Three sizes, optional mono
 * value read-out beneath.
 */
export interface AuSwatch extends Omit<UiComponent, 'type'> {
  type: 'au-swatch'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The colour to show — any CSS colour string. This is DATA (the token value being displayed). */
  value?: string
  /** The chip diameter. md is the default. */
  size?: 'md' | 'sm' | 'lg'
  /**
   * Alpha-0 — dims the fill and draws a checker, so "no paint" stays legible. (Named `alpha0`, not
   * `hidden`, which would collapse the element via the global attribute.)
   */
  alpha0?: boolean
  /** An optional mono value read-out rendered beneath the chip. */
  label?: string
}

/**
 * The interface for <au-switch>: a role=switch toggle — a token track + thumb. Monochrome: "on" is an
 * ink-1 track with a canvas thumb slid right. Form-associated. Emits `au-change {checked}`.
 */
export interface AuSwitch extends Omit<UiComponent, 'type'> {
  type: 'au-switch'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Whether the switch is on. Form-associated (participates in a native form + reset). */
  checked?: boolean
  /** Non-interactive + de-emphasized. Reflected as the `disabled` state. */
  disabled?: boolean
  /** Accessible name for the toggle (there is no visible label). Set on the inner control as aria-label. */
  label?: string
}

/**
 * <au-tab> — one tab of an <au-tabs> compound. Nest it as a child of <au-tabs>; it self-assigns the
 * tablist slot and takes its variant / orientation / active state from the parent. The default slot is
 * the label; optional `icon` (leading glyph), `badge` (trailing count), and `status` (a trailing
 * StatusDot — the only hue a tab may carry) slots. Its `value` matches the owning <au-tab-panel>.
 */
export interface AuTab extends Omit<UiComponent, 'type'> {
  type: 'au-tab'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** This tab's value — matches its <au-tab-panel> value and the <au-tabs> value. */
  value?: string
  /** Disable the tab (skipped by keyboard + pointer). */
  disabled?: boolean
}

/**
 * The interface for <au-tab-bar>: a scrolling row of tabs over a strip with edge scrims. Emits
 * `au-select {id}` / `au-close {id}` / `au-add`. The container owns drag-to-reorder.
 */
export interface AuTabBar extends Omit<UiComponent, 'type'> {
  type: 'au-tab-bar'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The tab model. The parent owns it; the bar renders + orders (pinned to front). */
  tabs?: AuTabBarItem[]
  /** The selected tab's id. The track reveals it on selection and when the available track size changes. */
  activeId?: string
  /** The id of the tab being dragged (the container sets it from its drag store); that cell lifts. */
  draggingId?: string
  /** Show the add (+) button in the track (emits `au-add`). */
  add?: boolean
  /** Whether tabs carry a close affordance + middle-click close. Default true. */
  closable?: boolean
}

/** One <au-tab-bar> tab: id (keys select/close), label, and optional status flags. */
export interface AuTabBarItem {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Optional shared au-icon identifier for the tab content, shown in the leading grip slot. */
  icon?: string
  /** This tab contains a nested container; show a group marker without changing selection or drag behavior. */
  group?: boolean
  /** Stable id the consumer maps back to on `au-select` / `au-close`. */
  id: string
  /** The tab label (a filename). Truncates with ellipsis; the full text rides the native tooltip. */
  label: string
  /** Unsaved changes — promotes the status dot to full ink. */
  dirty?: boolean
  /** Sorts to the front, drops the close, and is exempt from close / middle-click. */
  pinned?: boolean
  /** Structure-locked — drops grip + close and draws the lock hairline. */
  locked?: boolean
  /** Preview / transient (opened-not-kept) — the label renders italic. */
  isPreview?: boolean
  /** Suppresses the drag grip INDEPENDENTLY of remove. */
  moveLocked?: boolean
  /** Suppresses the close INDEPENDENTLY of move. */
  removeLocked?: boolean
}

/**
 * <au-tab-panel> — the content region for one <au-tab>. Nest it as a child of <au-tabs>; it
 * self-assigns the panel slot and shows only when its `value` matches the <au-tabs> value. The region
 * is unboxed — compose a Skeleton / EmptyState / Card inside it. The default slot is the content.
 */
export interface AuTabPanel extends Omit<UiComponent, 'type'> {
  type: 'au-tab-panel'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Matches the owning <au-tab> value. */
  value?: string
}

/**
 * Content icons use a matched glyph box and shared label gap; whole-tab dragging remains available.
 * The interface for <au-tab-strip-cell>: a single tab (grip · status/dirty dot · label · close/pin).
 * Borderless — selection uses fill and ink without changing label weight. Emits `au-activate` (body) and `au-close` (close affordance).
 */
export interface AuTabStripCell extends Omit<UiComponent, 'type'> {
  type: 'au-tab-strip-cell'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Optional shared au-icon identifier for the tab content, shown in the leading grip slot. */
  icon?: string
  /** This tab contains a nested container; show a group marker without changing selection or drag behavior. */
  group?: boolean
  /** The tab label (a filename). Truncates; the full text rides the native tooltip. */
  label: string
  /** Selected tab — fills and brightens without shifting label weight; never auto-shrinks. */
  active?: boolean
  /** Unsaved changes — shows a status dot; clean tabs have no dot. */
  dirty?: boolean
  /** Pinned — shows a pin glyph in place of the close, always visible. */
  pinned?: boolean
  /** Freeze the lifted "carried" drag look. */
  dragging?: boolean
  /** Structure-locked — implies move + remove locked and draws the lock hairline. */
  locked?: boolean
  /** Preview / transient — the label renders italic. */
  preview?: boolean
  /** Disable movement from the tab body and suppress its optional drag grip. */
  moveLocked?: boolean
  /** Suppress the close affordance (tab can't be closed). */
  removeLocked?: boolean
  /** Render an additional leading grip (default true). The tab body remains draggable unless move-locked or locked. */
  grip?: boolean
}

/**
 * <au-table> — the monochrome data grid. Slot <au-table-head> / <au-table-body> holding rows + cells;
 * columns align across rows via display:table, wrapped in a thin horizontal-scroll sliver. `dense`
 * tightens the vertical rhythm. Sortable headers (au-table-header-cell) + selectable rows (au-table-row)
 * are their own concern; the cross-shadow state (dense padding, hover/selected ink) rides inherited vars.
 */
export interface AuTable extends Omit<UiComponent, 'type'> {
  type: 'au-table'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Tighten the vertical rhythm — half-height cell padding. */
  dense?: boolean
}

/** <au-table-body> — the body rowgroup of <au-table>. Slot <au-table-row>s of <au-table-cell>. */
export interface AuTableBody extends Omit<UiComponent, 'type'> {
  type: 'au-table-body'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

/** <au-table-cell> — a body cell of <au-table>. `align="end"` right-aligns + tabular figures; `muted` dims it. */
export interface AuTableCell extends Omit<UiComponent, 'type'> {
  type: 'au-table-cell'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Cell alignment; `end` right-aligns + tabular figures. */
  align?: 'start' | 'end'
  /** Render the value one ink-step dimmer (secondary meta). */
  muted?: boolean
}

/** <au-table-head> — the header rowgroup of <au-table>. Slot <au-table-row>s of <au-table-header-cell>. */
export interface AuTableHead extends Omit<UiComponent, 'type'> {
  type: 'au-table-head'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

/**
 * <au-table-header-cell> — a header cell of <au-table>: a mono-uppercase eyebrow. `align="end"`
 * right-aligns; `sortable` makes the whole header a sort control (label + rotating caret) that emits
 * `au-sort`; `sortDir` (asc | desc) marks the active column and points the caret.
 */
export interface AuTableHeaderCell extends Omit<UiComponent, 'type'> {
  type: 'au-table-header-cell'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Column alignment; `end` right-aligns (numeric columns). */
  align?: 'start' | 'end'
  /** Render the whole header as a sort control (label + caret) that emits au-sort. */
  sortable?: boolean
  /** Active sort direction for this column (asc | desc); absent when it is not the sort key. */
  sortDir?: 'asc' | 'desc'
}

/**
 * <au-table-row> — a row of <au-table>. Slot <au-table-header-cell> (in a head) or <au-table-cell> (in a
 * body). `selectable` makes it a hover-lift + keyboard target that emits `au-select`; `selected` rests on
 * a surface tint. Emphasis is surface + ink, never a leading rail.
 */
export interface AuTableRow extends Omit<UiComponent, 'type'> {
  type: 'au-table-row'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Make the row a hover-lift + keyboard-activatable target that emits au-select. */
  selectable?: boolean
  /** Resting selected state — a surface lift (never a leading bar). */
  selected?: boolean
}

/**
 * <au-tabs> — the in-content tablist + tabpanels pattern. DISTINCT from au-tab-bar (the pane chrome
 * strip) and au-segmented-control (the bounded toggle). `variant` line (a sliding 2px ink underline
 * over a hairline baseline) or pill (a quiet surface fill, no tray). `orientation` vertical is a rail
 * whose active tab is a fill + weight (never a bar). Nest <au-tab> + <au-tab-panel> children (matched
 * by `value`); the root owns selection, roving focus, the sliding indicator, and aria. Emits
 * au-tab-change {value}.
 */
export interface AuTabs extends Omit<UiComponent, 'type'> {
  type: 'au-tabs'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** line = a sliding underline over a hairline baseline (page/section nav); pill = a quiet surface fill. */
  variant?: 'line' | 'pill'
  /** horizontal row (default) or vertical rail (fill-active, never a leading bar). */
  orientation?: 'horizontal' | 'vertical'
  /** automatic selects on arrow-key focus (default); manual requires Enter / Space. */
  activationMode?: 'automatic' | 'manual'
  /** active hides inactive panels (default); keep retains them. (Slotted panels are hidden, never unmounted.) */
  mount?: 'active' | 'keep'
  /** overflow affordance when the list is wider than its box. scroll = a scrolling track + edge scrims. */
  overflow?: 'none' | 'scroll' | 'menu' | 'both'
  /** The controlled active tab value (matches an <au-tab> / <au-tab-panel> value). */
  value?: string
  /** Accessible name for the tablist. */
  label?: string
}

/**
 * <au-tag> — a mono code-tag: a small monospaced label (frontmatter tags, code-ish chips). Content is
 * the default slot; `muted` recedes the text one ink step. Non-interactive.
 */
export interface AuTag extends Omit<UiComponent, 'type'> {
  type: 'au-tag'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Recede the text one ink step. */
  muted?: boolean
}

/**
 * The interface for <au-textarea>: a multiline text field mirroring au-input's chrome. Form-associated.
 * `mono` + `size` support a code/pattern well; `autoGrow` grows to a token cap then scrolls. Emits
 * `au-input` / `au-change`.
 */
export interface AuTextarea extends Omit<UiComponent, 'type'> {
  type: 'au-textarea'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The field text. Form-associated (participates in a native form + reset). */
  value?: string
  /** Placeholder shown when empty. */
  placeholder?: string
  /** Initial visible row count (the box grows with `resize` unless `autoGrow`). Default 3. */
  rows?: number
  /** Non-interactive + de-emphasized. Reflected as the `disabled` state. */
  disabled?: boolean
  /** Paints the danger border + focus ring and sets aria-invalid. Reflected as the `error` state. */
  error?: boolean
  /** Grow to fit content up to a token max-height, then scroll (disables the manual resize handle). */
  autoGrow?: boolean
  /** Monospace font — for a code / pattern well (ignore rules, snippets). Default is the sans body font. */
  mono?: boolean
  /** Font + padding step. `md` (default), `sm` (dense wells), `lg` (roomy). */
  size?: 'sm' | 'md' | 'lg'
  /** Native spellcheck. Turn OFF for code / pattern text where squiggles are noise. Default on. */
  spellcheck?: boolean
}

/**
 * Narrow containers place the action beneath the message while keeping dismissal at the top right.
 * The host bounded stack accepts scrollbar input; outside its bounds clicks pass through.
 * Host stack scrolling uses the theme focus hue and system focus color in forced colors.
 * Text-role fallbacks match the base ink palette without token stylesheets.
 * Long unbroken headings and descriptions wrap within the available content width.
 * <au-toast> — one floating toast card. Elev-5 fill + inset hairline + glass shadow; severity rides a
 * small leading tone DOT (ink/ok/warn/danger) — NEVER a bar or a fill. A heading, an optional
 * description (default slot), an optional trailing `action` slot, and a built-in × close (emits
 * au-close). The LOOK only: the host notification surface owns the claim, the queue, and the timers.
 */
export interface AuToast extends Omit<UiComponent, 'type'> {
  type: 'au-toast'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The toast headline (`title` is the reserved native tooltip, so this is `heading`, like au-banner). */
  heading?: string
  /** Severity, as a leading status dot only (never a bar/fill). ink is the neutral default. */
  tone?: 'ink' | 'ok' | 'warn' | 'danger'
  /** Show the × close affordance (emits au-close). Default on. */
  dismissible?: boolean
}

/**
 * <au-toggle-chip> — an interactive filter chip. The INTERACTIVE sibling of the display-only au-chip:
 * a toggleable pill (pressed / unpressed) with a status-or-advisory tone and an optional trailing
 * count. Emits au-toggle {pressed} when activated. For multi-select view filters — a severity facet,
 * an origin-kind facet — where each chip toggles independently (unlike the single-select
 * au-segmented-control).
 */
export interface AuToggleChip extends Omit<UiComponent, 'type'> {
  type: 'au-toggle-chip'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The chip text. */
  label?: string
  /** The tone signal — the same status/advisory range as au-status-dot. Neutral ink by default. */
  tone?: 'ink' | 'ok' | 'warn' | 'danger'
  /** An optional trailing count. */
  count?: number
  /** Whether the filter is active (on). Reflected. */
  pressed?: boolean
  /** Disable interaction. */
  disabled?: boolean
}

/**
 * Group related actions with native Tab navigation. Child controls retain their own arrow-key
 * behavior; this layout deliberately uses group semantics, not a composite toolbar. Choose
 * scroll for one unbroken action row or wrap for responsive rows. Floating material follows
 * the shared theme; selected paint belongs to the controls.
 */
export interface AuToolbar extends Omit<UiComponent, 'type'> {
  type: 'au-toolbar'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Bar height on the 4px grid: compact/dense/chrome = 28/32/40. */
  size?: 'dense' | 'compact' | 'chrome'
  /** docked = pane chrome on one hairline; floating = the elevated contextual pill. */
  variant?: 'docked' | 'floating'
  /** Explicit overflow: scroll preserves one row; wrap grows into multiple rows. */
  overflow?: 'scroll' | 'wrap'
  /** Dim + inert (no selection / read-only pane); the bar stays visible. */
  disabled?: boolean
}

/**
 * <au-toolbar-group> — a flex cluster of related controls inside an <au-toolbar>. `default` breathes
 * (space-2), `tight` hugs (space-1).
 */
export interface AuToolbarGroup extends Omit<UiComponent, 'type'> {
  type: 'au-toolbar-group'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Item gap inside the cluster: default = space-2 (8), tight = space-1 (4). */
  gap?: 'default' | 'tight'
}

/**
 * <au-toolbar-spacer> — a flex spacer (flex:1) inside an <au-toolbar>; it pushes the controls after it
 * to the far edge. No content.
 */
export interface AuToolbarSpacer extends Omit<UiComponent, 'type'> {
  type: 'au-toolbar-spacer'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

/**
 * The interface for <au-tooltip>: the whisper-tier label bubble — the smallest floating overlay surface.
 * side (pointing edge) + optional arrow; the label is slotted. Claims no overlay itself; a container floats it.
 */
export interface AuTooltip extends Omit<UiComponent, 'type'> {
  type: 'au-tooltip'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The edge the bubble points FROM: `top` (default, bubble above the anchor) / `right` / `bottom` / `left`. */
  side?: 'top' | 'right' | 'bottom' | 'left'
  /** Show the little pointer arrow tracking `side`. Default on. */
  arrow?: boolean
}

/**
 * <au-tree> — the grain-reduced container. The consumer slots <au-tree-item> children it emits from
 * its own loop; the tree provides structure. Items emit au-select on pointer or keyboard activation.
 * Uses shared tree typography and registry-aligned font defaults without a theme sheet; keyboard focus, arrow navigation, Home/End and type-ahead are supplied by the tree.
 */
export interface AuTree extends Omit<UiComponent, 'type'> {
  type: 'au-tree'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

/**
 * <au-tree-item> — a grain-reduced tree row. `label` for the text; nest <au-tree-item> children to
 * make a collapsible branch (`expanded` shows them). Emitted by the consumer's loop inside <au-tree>.
 * Dense rows use shared spacing/indent and resting, reading, quiet and selected ink roles.
 * Disclosure toggles on pointer press; keyboard focus, arrow navigation, Home/End and type-ahead are supplied by the tree.
 */
export interface AuTreeItem extends Omit<UiComponent, 'type'> {
  type: 'au-tree-item'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Row text. Render-resilient: absent renders empty. */
  label?: string
  /** Marks the row selected (styling + a11y). */
  selected?: boolean
  /** For a branch (has nested children), whether the children are shown. Ignored for a leaf. */
  expanded?: boolean
}

/**
 * The interface for <au-tree-row>: a file-tree row. `kind` folder/file, `level` indent, `open` /
 * `selected` / `dirty` / `disabled`. Identity glyph leads on the indent-step rail (`icon` overrides it);
 * the disclosure chevron trails after the label. Default-slot label. Emits au-activate + au-toggle.
 */
export interface AuTreeRow extends Omit<UiComponent, 'type'> {
  type: 'au-tree-row'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Folder (folder glyph + a trailing disclosure twist) or file (file glyph, no twist). Default file. */
  kind?: 'file' | 'folder'
  /** Nesting depth (0 = root). Drives the leading indent via `--au-tree-level`. */
  level?: number
  /** Folder disclosure state — rotates the twist, swaps to the open-folder glyph. */
  open?: boolean
  /** Current / active row — firms to surface-2 + a hairline ring (no bar), brightens the ink. */
  selected?: boolean
  /** Unsaved changes — a small ink dot at the trailing edge (never a rail). */
  dirty?: boolean
  /** Non-interactive + de-emphasized. Reflected as the `disabled` state; suppresses activation. */
  disabled?: boolean
}

/**
 * <au-typed-value-editor> — pass a resolved `schema` + `value`; the element renders a typed form and emits
 * `au-value-change` per edit + `au-value-complete` on submit. `schema` / `value` are opaque to the type
 * system (a recursive TS union the engine grammar can't express), so both are `opaque` here — the element's
 * own TS carries the real `ResolvedShape`.
 */
export interface AuTypedValueEditor extends Omit<UiComponent, 'type'> {
  type: 'au-typed-value-editor'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /**
   * The RESOLVED shape tree to edit (a `ResolvedShape`). Set as a PROPERTY (complex data), not an attribute.
   * Opaque to the type system — the element types it as `ResolvedShape`.
   */
  schema?: unknown
  /** The current value (a record map, or a scalar). Set as a PROPERTY. Records carry their own `type:`. */
  value?: unknown
  /**
   * Validation findings to display (a `ValueDiagnostic[]` from the core). Set as a PROPERTY. The element
   * never validates — the host runs `validate()` and passes results in; the element maps them to rows.
   */
  diagnostics?: unknown
  /**
   * The picker data source for reference / file / any slots: `(slotPath, query) => Promise<EditorOption[]>`.
   * A CALLBACK property (not a data field). Absent → references degrade to free text. The host wires it to
   * `readInstancesOf` / `readFiles`.
   */
  resolveOptions?: unknown
  /** Label for the submit affordance. */
  submitLabel?: string
}

/**
 * The interface for <au-viewer-switch>: the split affordance that re-shows a file in another projection.
 * The PRIMARY button switches to the viewer that renders the file (its name, or "Open with" for a
 * choice) and emits `au-activate`; the CHEVRON (shown when `has-more`) opens the secondary group of
 * file-consumers (radial/focal) and emits `au-more`. Names no projection; the projection labels it and
 * runs the `viewerSwitchSets` / `runViewerSwitch` helper. The document-action pill look; placement is the projection's.
 */
export interface AuViewerSwitch extends Omit<UiComponent, 'type'> {
  type: 'au-viewer-switch'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The primary button's visible text and accessible label. The sole rendering viewer's name, or "Open with" (default) for a choice. */
  primaryLabel?: string
  /** Show the chevron for the secondary group (file-consumers that are not viewers). Default off. */
  hasMore?: boolean
  /** Non-interactive + de-emphasized; suppresses both actions. */
  disabled?: boolean
}

/** One workspace-switcher row: id (the entry root, keys the switch) + name (shown in the menu). */
export interface AuWorkspaceItem {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Stable id the consumer maps back on `au-select` (the workspace entry root). */
  id: string
  /** The workspace name shown in the menu row (and its mark). */
  name: string
}

/**
 * The interface for <au-workspace-mark>: the workspace initial in a monochrome rounded tile. `name`'s
 * first glyph is the mark; it self-labels for a11y.
 */
export interface AuWorkspaceMark extends Omit<UiComponent, 'type'> {
  type: 'au-workspace-mark'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The workspace name — its first glyph becomes the mark and its a11y label. */
  name?: string
}

/**
 * The interface for <au-workspace-switcher>: the rail identity row + workspace menu. `name`/`current-id`
 * attrs + an `items` property; the menu claims host.overlay. Emits au-select/au-open-folder/au-new-workspace.
 */
export interface AuWorkspaceSwitcher extends Omit<UiComponent, 'type'> {
  type: 'au-workspace-switcher'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The current workspace name — the trigger's label and its mark. */
  name?: string
  /** The workspaces the menu offers (current + recents). Set as a PROPERTY. Render-resilient: empty. */
  items?: AuWorkspaceItem[]
  /** Which item id is the current workspace (reads as marked). Falls back to matching `name`. */
  currentId?: string
}
