// The interface CATALOG surface: the codegen'd consumer types for the known component NAMES.

// A consuming projection imports the typed props for a tag from HERE (e.g. `AuButton`) — the
// name + its shape — and depends on NO implementation. The active `component-set` provides the
// behavior at runtime. `UiComponent` is borrowed from `@arsumbris/component-contract` (the base
// every catalog subtype extends) via the codegen module map.

// Contract-only: this package ships no runtime code, only type-defs + their generated types.

import type { AuBadge, AuButton, AuCard, AuChevron, AuChip, AuCloseButton, AuCommandPalette, AuGripGlyph, AuIcon, AuIconButton, AuInput, AuNavItem, AuTreeRow, AuSectionHeader, AuNavGroup, AuPaneFrame, AuPaneHeader, AuSplitter, AuStatusDot, AuTabBar, AuTabStripCell, AuTree, AuTreeItem, AuWorkspaceMark, AuWorkspaceSwitcher, AuTag, AuPill, AuDivider, AuSpinner, AuScrollArea, AuEmptyState, AuCodeBlock, AuDiffLine, AuListRow, AuTable, AuTableHead, AuTableBody, AuTableRow, AuTableHeaderCell, AuTableCell, AuField, AuSegmentedControl, AuColorPicker, AuCheckbox, AuSwitch, AuRadioGroup, AuTextarea, AuNumberInput, AuSelect, AuBanner, AuAccordion, AuAccordionItem, AuOutputLog, AuTooltip, AuToggleChip, AuToast, AuMenu, AuMenuItem, AuModal, AuSwatch, AuCodeSample, AuMeter, AuSkeleton, AuSlider, AuBreadcrumb, AuToolbar, AuToolbarGroup, AuToolbarSpacer, AuDetailList, AuDropZone, AuStepper, AuPagination, AuCombobox, AuDrawer, AuKbd, AuTabs, AuTab, AuTabPanel, AuPopover, AuHovercard, AuViewerSwitch, AuTypedValueEditor, AuCommandItem, AuTabBarItem, AuWorkspaceItem, AuSegmentItem, AuRadioItem, AuSelectOption, AuBreadcrumbItem, AuDetailItem, AuStepItem, AuComboboxOption } from './generated'
export type { AuBadge, AuButton, AuCard, AuChevron, AuChip, AuCloseButton, AuCommandPalette, AuGripGlyph, AuIcon, AuIconButton, AuInput, AuNavItem, AuTreeRow, AuSectionHeader, AuNavGroup, AuPaneFrame, AuPaneHeader, AuSplitter, AuStatusDot, AuTabBar, AuTabStripCell, AuTree, AuTreeItem, AuWorkspaceMark, AuWorkspaceSwitcher, AuTag, AuPill, AuDivider, AuSpinner, AuScrollArea, AuEmptyState, AuCodeBlock, AuDiffLine, AuListRow, AuTable, AuTableHead, AuTableBody, AuTableRow, AuTableHeaderCell, AuTableCell, AuField, AuSegmentedControl, AuColorPicker, AuCheckbox, AuSwitch, AuRadioGroup, AuTextarea, AuNumberInput, AuSelect, AuBanner, AuAccordion, AuAccordionItem, AuOutputLog, AuTooltip, AuToggleChip, AuToast, AuMenu, AuMenuItem, AuModal, AuSwatch, AuCodeSample, AuMeter, AuSkeleton, AuSlider, AuBreadcrumb, AuToolbar, AuToolbarGroup, AuToolbarSpacer, AuDetailList, AuDropZone, AuStepper, AuPagination, AuCombobox, AuDrawer, AuKbd, AuTabs, AuTab, AuTabPanel, AuPopover, AuHovercard, AuViewerSwitch, AuTypedValueEditor, AuCommandItem, AuTabBarItem, AuWorkspaceItem, AuSegmentItem, AuRadioItem, AuSelectOption, AuBreadcrumbItem, AuDetailItem, AuStepItem, AuComboboxOption }

export type { AuSettingsSection } from './generated'
