// Generated by the component-layer JSX codegen (`pnpm gen:react`). Do not edit by hand.
//
// REACT-TARGET augmentation: types each ui-component TAG for TSX by deriving its props from the NEUTRAL
// interfaces in ./generated — for residual INTRINSIC `<au-*>` usage + children typing. Svelte/vanilla
// type custom elements differently, so this is the react sub-output only.
//
// The PAVED PATH for React consumers is the generated WRAPPERS (`./react`, re-exporting this file), which
// set props as element properties and wire events as typed `onAuXxx` props — the two frictions this
// augmentation cannot solve (React sets a dashed-attribute prop unreliably, and does not auto-attach
// custom-element listeners). The wrappers render the tag string and import no set class, so live set-swap
// holds.
import type { AuAccordion, AuAccordionItem, AuBadge, AuBanner, AuBreadcrumb, AuButton, AuCard, AuCheckbox, AuChevron, AuChip, AuChordInput, AuCloseButton, AuCodeBlock, AuCodeSample, AuColorPicker, AuCombobox, AuCommandPalette, AuDetailList, AuDiffLine, AuDivider, AuDrawer, AuDropZone, AuEmptyState, AuField, AuGripGlyph, AuHovercard, AuIcon, AuIconButton, AuInput, AuKbd, AuListRow, AuMenu, AuMenuItem, AuMeter, AuModal, AuNavGroup, AuNavItem, AuNumberInput, AuOutputLog, AuPagination, AuPaneFrame, AuPaneHeader, AuPaneTarget, AuPill, AuPopover, AuRadioGroup, AuScrollArea, AuSectionHeader, AuSegmentedControl, AuSelect, AuSettingsSection, AuSkeleton, AuSlider, AuSpinner, AuSplitter, AuStatusDot, AuStepper, AuSwatch, AuSwitch, AuTab, AuTabBar, AuTabPanel, AuTabStripCell, AuTable, AuTableBody, AuTableCell, AuTableHead, AuTableHeaderCell, AuTableRow, AuTabs, AuTag, AuTextarea, AuToast, AuToggleChip, AuToolbar, AuToolbarGroup, AuToolbarSpacer, AuTooltip, AuTree, AuTreeItem, AuTreeRow, AuTypedValueEditor, AuViewerSwitch, AuWorkspaceMark, AuWorkspaceSwitcher } from './generated'
import type { DetailedHTMLProps, HTMLAttributes } from 'react'

/** JSX props for a custom-element tag: the neutral data-in props (minus the `type` discriminant)
 *  plus the standard React host-element attributes (className / style / ref / children / …). */
type Props<T> = DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement> & Omit<T, 'type'>

declare module 'react' {
  namespace JSX {
    interface IntrinsicElements {
      'au-accordion': Props<AuAccordion>
      'au-accordion-item': Props<AuAccordionItem>
      'au-badge': Props<AuBadge>
      'au-banner': Props<AuBanner>
      'au-breadcrumb': Props<AuBreadcrumb>
      'au-button': Props<AuButton>
      'au-card': Props<AuCard>
      'au-checkbox': Props<AuCheckbox>
      'au-chevron': Props<AuChevron>
      'au-chip': Props<AuChip>
      'au-chord-input': Props<AuChordInput>
      'au-close-button': Props<AuCloseButton>
      'au-code-block': Props<AuCodeBlock>
      'au-code-sample': Props<AuCodeSample>
      'au-color-picker': Props<AuColorPicker>
      'au-combobox': Props<AuCombobox>
      'au-command-palette': Props<AuCommandPalette>
      'au-detail-list': Props<AuDetailList>
      'au-diff-line': Props<AuDiffLine>
      'au-divider': Props<AuDivider>
      'au-drawer': Props<AuDrawer>
      'au-drop-zone': Props<AuDropZone>
      'au-empty-state': Props<AuEmptyState>
      'au-field': Props<AuField>
      'au-grip-glyph': Props<AuGripGlyph>
      'au-hovercard': Props<AuHovercard>
      'au-icon': Props<AuIcon>
      'au-icon-button': Props<AuIconButton>
      'au-input': Props<AuInput>
      'au-kbd': Props<AuKbd>
      'au-list-row': Props<AuListRow>
      'au-menu': Props<AuMenu>
      'au-menu-item': Props<AuMenuItem>
      'au-meter': Props<AuMeter>
      'au-modal': Props<AuModal>
      'au-nav-group': Props<AuNavGroup>
      'au-nav-item': Props<AuNavItem>
      'au-number-input': Props<AuNumberInput>
      'au-output-log': Props<AuOutputLog>
      'au-pagination': Props<AuPagination>
      'au-pane-frame': Props<AuPaneFrame>
      'au-pane-header': Props<AuPaneHeader>
      'au-pane-target': Props<AuPaneTarget>
      'au-pill': Props<AuPill>
      'au-popover': Props<AuPopover>
      'au-radio-group': Props<AuRadioGroup>
      'au-scroll-area': Props<AuScrollArea>
      'au-section-header': Props<AuSectionHeader>
      'au-segmented-control': Props<AuSegmentedControl>
      'au-select': Props<AuSelect>
      'au-settings-section': Props<AuSettingsSection>
      'au-skeleton': Props<AuSkeleton>
      'au-slider': Props<AuSlider>
      'au-spinner': Props<AuSpinner>
      'au-splitter': Props<AuSplitter>
      'au-status-dot': Props<AuStatusDot>
      'au-stepper': Props<AuStepper>
      'au-swatch': Props<AuSwatch>
      'au-switch': Props<AuSwitch>
      'au-tab': Props<AuTab>
      'au-tab-bar': Props<AuTabBar>
      'au-tab-panel': Props<AuTabPanel>
      'au-tab-strip-cell': Props<AuTabStripCell>
      'au-table': Props<AuTable>
      'au-table-body': Props<AuTableBody>
      'au-table-cell': Props<AuTableCell>
      'au-table-head': Props<AuTableHead>
      'au-table-header-cell': Props<AuTableHeaderCell>
      'au-table-row': Props<AuTableRow>
      'au-tabs': Props<AuTabs>
      'au-tag': Props<AuTag>
      'au-textarea': Props<AuTextarea>
      'au-toast': Props<AuToast>
      'au-toggle-chip': Props<AuToggleChip>
      'au-toolbar': Props<AuToolbar>
      'au-toolbar-group': Props<AuToolbarGroup>
      'au-toolbar-spacer': Props<AuToolbarSpacer>
      'au-tooltip': Props<AuTooltip>
      'au-tree': Props<AuTree>
      'au-tree-item': Props<AuTreeItem>
      'au-tree-row': Props<AuTreeRow>
      'au-typed-value-editor': Props<AuTypedValueEditor>
      'au-viewer-switch': Props<AuViewerSwitch>
      'au-workspace-mark': Props<AuWorkspaceMark>
      'au-workspace-switcher': Props<AuWorkspaceSwitcher>
    }
  }
}
