// Generated by @arsumbris/type-codegen. Do not edit by hand.
// Source: au-engine type-defs, repo `column`.

import type { ContainerSlot, GroupingContainer } from '@arsumbris/au-host-sdk'

/** A branded wikilink string. The brand records the referenced type-def name(s). */
export type Ref<T extends string> = string & { readonly __ref: T }

/** A branded wikilink to a type-def (the def axis of `T*`), distinct from an instance `Ref`. The brand records the def-axis bound. */
export type DefRef<T extends string> = string & { readonly __defRef: T }

export interface Column extends Omit<GroupingContainer, 'type'> {
  type: 'column'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  items: Array<Ref<'mountable'> | ColumnSlot>
  /**
   * Render each item's grip, label, close and collapse controls. Default true.
   * False hides all item headers and displays their content expanded, without changing slot move/remove rules or drop targets.
   */
  showItemHeaders?: boolean
  /**
   * Item controls: always, hover/focus edge handle, or hidden. When present overrides showItemHeaders.
   * Hover mode keeps content expanded and does not absorb child tab strips; touch shows the handle.
   */
  itemHeaders?: 'always' | 'hover' | 'hidden'
  /** Add-pane button presentation. Default always. Hover reveals on pointer hover or keyboard focus; touch keeps it visible. Hidden removes only this button, not drop targets. */
  addButton?: 'always' | 'hover' | 'hidden'
  /**
   * Offer the centre wrap-into-a-group zone on a drop. Absent = true.
   * The EMISSION half of a refusal, and the reason it is not `admits`. `admits` is per-slot and
   * refuses AFTER the zone was offered; this suppresses the zone entirely, and it covers children
   * authored LATER, which arrive in a bare slot no per-slot rule governs. Both layers are wanted.
   */
  allowWrap?: boolean
}

/** A column item: the shared slot rules, plus the size and collapsed state column renders. */
export interface ColumnSlot extends Omit<ContainerSlot, 'type'> {
  type: 'column-slot'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The item's extent along the column axis, in px. Absent = column's default. */
  size?: number
  /**
   * The item is collapsed to its header. A collapsed item still has its occupant and its
   * rules.
   */
  collapsed?: boolean
}
