// Generated by @arsumbris/type-codegen. Do not edit by hand.
// Source: au-engine type-defs, repo `au-host-sdk`.

/** A branded wikilink string. The brand records the referenced type-def name(s). */
export type Ref<T extends string> = string & { readonly __ref: T }

/** A branded wikilink to a type-def (the def axis of `T*`), distinct from an instance `Ref`. The brand records the def-axis bound. */
export type DefRef<T extends string> = string & { readonly __defRef: T }

export interface BarProjection extends Omit<Projection, 'type'> {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  order?: number
  minSize?: number
  overflowEligible?: boolean
}

/** One compact render size, in px. Owned by au-host-sdk. Generates the exported `Breakpoint` interface. */
export interface Breakpoint {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The px width a width-collapsing container (e.g. the sandwich) sizes the position to. */
  width?: number
  /** The px height a height-collapsing container sizes the position to. */
  height?: number
}

/** The compact render sizes a projection can render at. */
export interface BreakpointsMeta {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /**
   * The compact sizes this projection supports. Non-empty: a projection that declares this meta
   * supports at least one.
   */
  breakpoints: [Breakpoint, ...Array<Breakpoint>]
}

/**
 * Type-level PRESENTATION for an intent that is invocable as a user COMMAND. Declared on the intent
 * TYPE-DEF (the intent IS the command; one intent is handled by many projections, so a per-projection
 * default would conflict). Carrying this meta is the OPT-IN: an intent WITH a `command-meta` surfaces in
 * the command palette; an intent WITHOUT one is fired only internally, never listed. The command's
 * PARAMETERS are the intent's own payload fields (read from the type graph), so none are declared here.
 * The palette (human) and the agent intent-as-tool bridge read the same declaration.
 */
export interface CommandMeta {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The command's display name, an imperative verb phrase (e.g. "Save composition"). */
  label: string
  /**
   * OPTIONAL leading icon, a SEMANTIC ROLE name (e.g. `save`, `delete`), NOT a component-set glyph name —
   * so an intent has a KNOWN BASIS independent of any set (an intent may run where a given set is not
   * shipped). The role set must be a SHARED NAMED ENUM the intent layer owns, which needs the engine's
   * named-enum feature (a referenceable enum type, not an inline per-field literal list). Until then this
   * is a free String, unvalidated.
   * Icon identifier; the current schema accepts a string.
   */
  icon?: string
  /** OPTIONAL grouping label for the palette (e.g. "Composition"). Commands sharing a category group together. */
  category?: string
}

export interface Composition extends Omit<MountableBase, 'type'> {
  type: 'composition'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /**
   * A typed document naming a set of windows and a flat pool of referenced projection records. The
   * host's canonical form for a saved, mountable workspace, across one or more OS windows.
   * The windows the host opens on load, each a `[[^^id]]` into `projections` naming a `window` record.
   * One is `primary` (surface 0, the main window); the rest are secondary surfaces of the SAME
   * composition. Non-empty: a composition always has at least the primary window. Reopening a saved
   * composition reopens its windows.
   */
  windows: [Ref<'window'>, ...Array<Ref<'window'>>]
  /**
   * The flat pool. Each element is an inline `mountable` record (a projection, or a `window` site)
   * carrying a `^:` block-id + an explicit `type:`; containers + windows reference siblings by `[[^^id]]`.
   * The tree structure lives in the reference graph, not in nesting.
   */
  projections?: Mountable[]
  /**
   * The routing-config bundle: ambient defaults, explicit wires, per-node reachability, and the
   * initial-focus seed. A first-class part of the composition contract (not a mixin); left unset is
   * absence. Its type is a `composition-config` aspect, so a projection's routing edit-right is
   * bounded by the unchanged `edits: type<composition-config>*`.
   */
  'intent-routing'?: IntentRouting
  /**
   * The per-file-kind default viewer config: which viewer opens each kind by default. A standalone
   * `composition-config` aspect (sibling to `intent-routing`); left unset means every ambiguous open
   * pickers until a default is authored. Opens-meta declares only ELIGIBILITY; this is the decision.
   */
  'viewer-defaults'?: ViewerDefaults
  /**
   * The composition-wide default placeholder an EMPTY slot resolves to (the `configured` rung of the
   * empty-slot ladder). A standalone `composition-config` aspect (sibling to the above); a per-slot
   * `container-slot.placeholder` overrides it. Left unset means an empty slot falls to sole / ask.
   */
  'slot-defaults'?: SlotDefaults
  /**
   * The grouping config: which `grouping-container` a new group is built with (`group-into`), and whether
   * new document panes arrive grouped (`group-new-panes`). A standalone `composition-config` aspect
   * (sibling to the two above). Left unset means a wrap asks the chooser
   * and documents open bare.
   */
  grouping?: Grouping
  /**
   * The ORDERED list of active keymaps. A chord resolves over the merge of these files (global + the
   * focus-scoped ones whose type is focused), focus-first with list order breaking ties. Drop an entry
   * to turn a keymap off. A referenced-record list of shareable keymap FILES, NOT a `composition-config`
   * aspect. Left unset means the composition binds no keys.
   */
  keymaps?: [Ref<'keymap'>, ...Array<Ref<'keymap'>>]
  /**
   * Milliseconds to wait for a key-sequence continuation. Zero disables automatic expiry.
   * Omitted retains the dispatcher default. Inspection pauses and refills this window.
   */
  'key-sequence-timeout-ms'?: number
}

export interface CompositionConfig {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface ContainerNode {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

/**
 * A projection that holds and lays out child projections. Identity only — what a container IS,
 * never what it declares.
 */
export interface ContainerProjection extends Omit<Projection, 'type'> {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

/**
 * The POSITION a child occupies in a container, carrying what belongs to the position
 * rather than to the child. Every field is optional: a slot with nothing to say is not
 * written at all, and the child sits bare in the container's field instead.
 */
export interface ContainerSlot extends Omit<ContainerNode, 'type'> {
  type: 'container-slot'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /**
   * The occupant, BY REFERENCE (`[[^^id]]` into the pool, or `[[file]]` naming a composition).
   * Reference-only: an inline record here is a type error. ABSENT is an empty slot that still
   * carries its rules — which is how a constrained-but-unfilled region stays constrained, rather
   * than silently losing its pin the moment it is emptied.
   */
  child?: Ref<'mountable'>
  /**
   * What may occupy this slot; absent admits anything. It governs every occupant-TYPE
   * change, not only a direct swap: a centre-wrap writes a CONTAINER here and a dissolve
   * writes the lone CHILD here, so both answer to it. Checked by CLOSURE, never by exact
   * type match. `[+]`, so a declared `admits` names at least one type — an empty one is
   * not expressible, deliberately, since a slot nothing may occupy has no use site.
   */
  admits?: [DefRef<'projection'>, ...Array<DefRef<'projection'>>]
  /**
   * The PER-SLOT default placeholder this position resolves to when EMPTY — the local override of the
   * composition-wide `slot-defaults.placeholder`. The empty-slot resolver reads
   * `(this ?? composition slot-defaults.placeholder)` as its `configured` rung (configured > sole > ask).
   * A def-ref to a `placeholder-projection` type; absent falls back to the composition default, then the
   * count. It belongs on the POSITION beside `admits` / `fixed` / `label`: "what shows when I am empty" is
   * a property of the slot, not of any child.
   */
  placeholder?: DefRef<'placeholder-projection'>
  /**
   * The occupant may not be dragged out, closed, or displaced by a restructure. Its reach
   * is DEEP: ANY operation that would displace the occupant is refused, not merely a
   * drag. So a `fixed` slot can never be emptied. It does NOT freeze a subtree — a fixed
   * slot may hold a container whose own slots are free, which is how "the frame is fixed,
   * its contents can still grow" needs no vocabulary of its own.
   */
  fixed?: boolean
  /**
   * What the container's chrome TITLES this position. Absent falls back to the occupant's
   * human name, and only when the occupant draws no chrome of its own — so an unlabelled
   * position holding a container shows nothing, which is how stacked mastheads stay fixed
   * without a suppression rule of its own.
   *
   * It is a POSITION's name, not the occupant's, for the same reason `size` and `collapsed`
   * are: a region authored "Sidebar" keeps reading "Sidebar" when a different projection is
   * dragged in. Titling by the occupant's TYPE is what made a sandwich holding a column
   * render "column" above the column's own item headers.
   */
  label?: string
  /**
   * Draw NO per-child header/chrome at this position. For a self-chrome occupant — one that
   * draws its own top band, like a rail — the container's region header would stack a second bar
   * over the occupant's own (the "double chrome"); setting this drops it.
   *
   * A CONTAINER MUST CHOOSE TO IMPLEMENT IT. It is offered on the base because "does the container
   * frame this child" is a universal slot question, but honouring it is per-container: a container
   * that draws no per-child header (or whose chrome is not separable) simply IGNORES this field.
   *
   * ORTHOGONAL to the other fields, each keeping its own job. It hides the header ONLY — it does
   * not lock the position (`fixed` still enforces re-parenting), does not constrain the occupant
   * (`admits` still applies), and does not touch layout (a hidden-header occupant still sizes and
   * collapses). `label` becomes moot, since nothing displays it. A self-chrome shell position that
   * must also be pinned sets `hideHeader: true` AND `fixed: true`.
   */
  hideHeader?: boolean
}

export interface FiresIntentMeta {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  fires: DefRef<'intent'>[]
}

export interface Grouping extends Omit<CompositionConfig, 'type'> {
  type: 'grouping'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /**
   * Which grouping container a new group is built with — a center-zone drop wrap, and (with
   * `group-new-panes`) a new document's arrival group. A DEF-REF bounded to `grouping-container`, so the
   * ENGINE validates the target IS a group container: a value naming a non-grouping container (bento) or
   * an absent type is a load error, not a drop that silently does nothing. The value is a wikilink to the
   * type-def, e.g. `group-into: "[[tabs]]"`. Absent, and with >=2 grouping containers eligible, a WRAP
   * asks the host chooser and a document ARRIVES BARE (never a silent name-sort default).
   */
  'group-into'?: DefRef<'grouping-container'>
  /**
   * When true, a newly-opened document pane ARRIVES wrapped in a group (its own tab strip / title) rather
   * than bare, grouped into `group-into`. A composition-level policy (the "which" beside the "whether"),
   * not a per-container field. Absent = documents open bare. With no `group-into` to resolve the container
   * unambiguously, a new document arrives bare rather than asking on every open.
   */
  'group-new-panes'?: boolean
}

/**
 * A container that can hold N children as ONE node — so it can be a drop-to-group target and the
 * container a new group is built with. Identity only: what a container IS, like container-projection.
 */
export interface GroupingContainer extends Omit<ContainerProjection, 'type'> {
  type: 'grouping-container'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface HandlesIntentMeta {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  handles?: DefRef<'intent'>[]
  handlesTargeted?: DefRef<'intent'>[]
}

/**
 * The base intent: a typed command fired into a scope. Concrete subtypes add payload fields.
 * The host routes by the type discriminant against declared capabilities. Never persisted.
 */
export interface Intent {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface IntentDefault {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  intent: DefRef<'intent'>
  roles: [DefRef<'projection'>, ...Array<DefRef<'projection'>>]
  mode?: 'priority' | 'whitelist' | 'block'
  source?: DefRef<'projection'>
}

export interface IntentReachRule {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /**
   * The node whose ambient reachability this rule sets, a pool `[[^^id]]` reference. Its type-def must
   * DECLARE the `intent` below as a handled input port (`handles-intent-meta`) — you can only close a port
   * the node actually has.
   */
  node: Ref<'projection'>
  /**
   * The intent this rule governs, a def-ref to an `intent` subtype (`intent: "[[open-intent::intent]]"`).
   * Same-repo bare here (`intent` is the host-sdk base). Engine-validated against the type graph.
   */
  intent: DefRef<'intent'>
  /**
   * The node's reachability for this intent. `wire-only`: it receives the intent ONLY via an explicit wire,
   * and ambient / MRU delivery skips it. `ambient`: the default — ambient delivery reaches it (same as no
   * rule), kept as an explicit value so the record is self-describing. (String-valued, NOT `on`/`off`, which
   * YAML coerces to booleans.)
   */
  reachability: 'ambient' | 'wire-only'
}

export interface IntentRouting extends Omit<CompositionConfig, 'type'> {
  type: 'intent-routing'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /**
   * The routing-config bundle a composition carries as its `intent-routing` field: ambient
   * defaults, explicit wires, per-node reachability, and the initial-focus seed.
   * Rung 3 — per ambient intent, its target role-kinds + scope mode. The host reads these
   * off the composition, resolves each rule's roles to mounted nodes by type-closure, and
   * scopes the focus-MRU candidate walk to them.
   */
  defaults?: IntentDefault[]
  /**
   * Rung 1 — explicit per-connection routings (the switchboard's stored form). A wire names
   * specific pool RECORDS, overriding an intent's default reach for that one (source, intent)
   * connection. Where no wire exists, default routing is untouched.
   */
  wires?: IntentWire[]
  /**
   * Rung 2 — per-(node, intent) ambient reachability. A rule can CLOSE a handling node to
   * ambient / MRU delivery (`wire-only`), so it receives that intent ONLY via an explicit wire.
   * A composition with none leaves every handling node ambient-reachable (today's behaviour).
   */
  reach?: IntentReachRule[]
  /**
   * The role focused on load, so the FIRST ambient open lands deterministically — a pinned
   * EMPTY editor group (never focused) can be the default open target. A projection KIND
   * def-ref (same-repo bare); if several nodes play it, the first by tree order seeds the
   * focus channel.
   */
  'initial-focus'?: DefRef<'projection'>
}

/**
 * Type-level routing metadata for an intent: how the host DISPATCHES a fired intent of this type.
 * Declared on the intent TYPE-DEF, never an instance (intents are ephemeral, never persisted), so
 * "how does this intent route" is a static type-graph fact. Codegen threads it onto every fired
 * payload; the runtime router reads it per fire, and an agent can read it off the type graph before firing.
 */
export interface IntentRoutingMeta {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /**
   * The dispatch mechanism.
   * - `routed`: a command consumed ONCE by the first handler that claims it.
   * - `broadcast`: an event fanned out to EVERY capable handler, with no claim and no ordering.
   */
  kind: 'routed' | 'broadcast'
  /**
   * For a `routed` intent, WHICH candidates it considers (absent for `broadcast` — fan-out is unordered).
   * - `ambient`: every capable handler tree-wide, most-recently-focused first. A GLOBAL route.
   * - `firer-relative`: only the firer's OWN ancestor chain. Scoped to the firer's container.
   *
   * They differ on the UNHANDLED outcome, and the host relies on it. An `ambient` intent that nobody
   * claims found no taker ANYWHERE, so the host surfaces it (an open with no home raises the open
   * chooser). A `firer-relative` intent that nobody claims just means the firer's own context does not
   * support it — there is no global fallback by design, so it is the expected terminal outcome and stays
   * SILENT. A firer that must know its intent landed checks `fire`'s claimed return instead.
   */
  dispatch?: 'ambient' | 'firer-relative'
}

export interface IntentWire {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /**
   * The firing projection record, a pool `[[^^id]]` reference. Its type-def must DECLARE the
   * `intent` below as an output port (`fires-intent-meta`); the overlay draws a cable only
   * from a declared fired intent.
   */
  source: Ref<'projection'>
  /**
   * The fired intent, a def-ref to an `intent` subtype (`intent: "[[open-intent::intent]]"`).
   * Engine-validated against the type graph — a typo is a validation error, not a silent
   * misroute, the payoff of reifying the map key as a field. Same-repo bare (`intent` is the
   * host-sdk base); a specific command is `::intent`-qualified at the value.
   */
  intent: DefRef<'intent'>
  /**
   * The recipient projection records, pool `[[^^id]]` references. Non-empty: a wire with no
   * recipients is meaningless. The wire's targets ARE the recipients, replacing the default
   * selection — a `once` intent WIDENS to the whole set, an `all` intent NARROWS to it.
   */
  targets: [Ref<'projection'>, ...Array<Ref<'projection'>>]
  /**
   * How a `once` (routed) intent's wire disposes a non-claim. `strict` (the default when
   * absent): deliver to the recipients ONLY; none handling falls to the existing `unhandled`
   * report (fail CLOSED, never widened). `fallback`: then the default MRU walk, EXCLUDING the
   * recipients already tried. IGNORED for an `all` (broadcast) intent, which never claims.
   */
  mode?: 'strict' | 'fallback'
}

/**
 * A chord modifier. `mod` is the platform accelerator, so one keybind is cross-platform.
 *
 * - `mod`: the platform accelerator — ⌘ on macOS, Ctrl elsewhere
 * - `ctrl`: raw Control, distinct from `mod` on macOS
 * - `alt`: Alt / Option
 * - `shift`: Shift
 */
export type KeyModifier = 'mod' | 'ctrl' | 'alt' | 'shift'

export type KeyName = 'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z' | 'digit0' | 'digit1' | 'digit2' | 'digit3' | 'digit4' | 'digit5' | 'digit6' | 'digit7' | 'digit8' | 'digit9' | 'f1' | 'f2' | 'f3' | 'f4' | 'f5' | 'f6' | 'f7' | 'f8' | 'f9' | 'f10' | 'f11' | 'f12' | 'arrowup' | 'arrowdown' | 'arrowleft' | 'arrowright' | 'enter' | 'tab' | 'escape' | 'space' | 'backspace' | 'delete' | 'home' | 'end' | 'pageup' | 'pagedown' | 'minus' | 'equal' | 'bracketleft' | 'bracketright' | 'backslash' | 'semicolon' | 'quote' | 'backquote' | 'comma' | 'period' | 'slash'

/** One keybind: the chord that triggers it, and the intent (command) it fires. */
export interface Keybind {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /**
   * The chord, an ordered SEQUENCE of keystrokes. One step is the common case; several form a chord
   * sequence (⌘K ⌘S).
   */
  chord: [Keystroke, ...Array<Keystroke>]
  /**
   * The command to fire — a def-ref to an `intent` subtype, cross-repo capable. Crossing a peer's intent
   * needs the keymap's repo to declare that dep (the peer gate).
   */
  intent: DefRef<'intent'>
  /**
   * Optional focus narrowing for THIS keybind, overriding the keymap file's own `when`. The keybind is
   * active only while a projection of one of these types holds focus.
   */
  when?: DefRef<'projection'>[]
}

/**
 * A keymap file: a set of keybinds and one activation scope. Global when `when` is absent, else active
 * only while a projection of one of the named types holds focus.
 */
export interface Keymap {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /**
   * Absent = global (always active). Present = active only while a projection of one of these types holds
   * focus. The file's default scope; a keybind may narrow it further with its own `when`.
   */
  when?: DefRef<'projection'>[]
  /** The keybinds this map declares. Non-empty. */
  keybinds: [Keybind, ...Array<Keybind>]
}

/**
 * One keystroke of a chord: a set of modifiers plus one key, matched by equality against a canonicalized
 * `event.code`.
 */
export interface Keystroke {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** The modifiers held, a set. Absent means no modifiers. */
  mods?: KeyModifier[]
  /**
   * The physical key, a canonical name from `event.code` (layout-stable). A closed vocabulary, so a typo
   * is a load error.
   */
  key: KeyName
}

export interface MountableBase {
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

/**
 * A thing the host can mount by reference: a projection (renders), a composition (names windows), or a
 * window (an OS surface holding a view). A sealed family of those three branches; child slots reference
 * this base as `mountable*`.
 */
export type Mountable = Projection | Composition | Window

/** Which file content a projection can OPEN — the content-routing axis, distinct from the code locator. */
export interface OpensMeta {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /**
   * The file extensions this viewer opens, no leading dot. `*` means any file (the universal
   * fallback). Non-empty: a viewer that declares this meta opens at least one thing.
   */
  opens: [string, ...Array<string>]
}

export interface PaneProjection extends Omit<Projection, 'type'> {
  type: 'pane-projection'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface PlaceholderProjection extends Omit<Projection, 'type'> {
  type: 'placeholder-projection'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface Projection extends Omit<MountableBase, 'type'> {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

/** How a projection names itself to a human — its display title, distinct from its type identity. */
export interface ProjectionPresentationMeta {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  title: string
}

export interface ProjectionRuntimeMeta {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  entry: string
  contractVersion: number
  export?: string
  customTokenEntry?: [string, ...Array<string>]
  sharedDeps?: [SharedDepRange, ...Array<SharedDepRange>]
}

export interface RawTextSurfaceMeta {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface SharedDepRange {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  specifier: string
  range: string
}

export interface SlotDefaults extends Omit<CompositionConfig, 'type'> {
  type: 'slot-defaults'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /**
   * The composition-wide default placeholder an empty slot resolves to, unless a slot overrides it.
   * The default placeholder-projection type for every empty slot in this composition, a def-ref
   * (`placeholder: "[[placeholder-picker::placeholder-picker]]"`). A per-slot `container-slot.placeholder`
   * overrides it. Unset → the resolver falls to sole / ask.
   */
  placeholder?: DefRef<'placeholder-projection'>
}

/**
 * A container that arranges its N children SPATIALLY (recursive splits, free 2D placement) rather than
 * STACKING them — a grouping container's spatial sibling. A WRAP TARGET (the wrap action's "Arrange"
 * family), but deliberately NOT a `grouping-container`. Identity only: what a container IS, like
 * container-projection.
 */
export interface SpatialContainer extends Omit<ContainerProjection, 'type'> {
  type: 'spatial-container'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface StatusProjection extends Omit<BarProjection, 'type'> {
  type: 'status-projection'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface ViewerDefault {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /**
   * The file kind this default applies to: a bare extension (no dot, `md`) or `*` (any file). Matched
   * against the opened file's extension at resolution.
   */
  opens: string
  /**
   * The viewer projection type that opens this kind by default, a def-ref (`viewer: "[[editor-pane::editor]]"`).
   * Same-repo bare (`projection` is the host-sdk base); a specific viewer is `::repo`-qualified at the value.
   */
  viewer: DefRef<'projection'>
}

export interface ViewerDefaults extends Omit<CompositionConfig, 'type'> {
  type: 'viewer-defaults'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /**
   * The per-file-kind default viewer config a composition carries as its `viewer-defaults` field: which
   * viewer opens each kind by default.
   * The default viewer per file kind, one `viewer-default` record each (kind -> viewer). A composition
   * with none pickers on every ambiguous open until a default is authored.
   */
  defaults?: ViewerDefault[]
}

/**
 * An OS window surface holding one root view by reference. A first-class pool node, so cross-window is
 * cross-pane. Its own sealed branch of `mountable` — a site, not content and not a layout.
 */
export interface Window extends Omit<MountableBase, 'type'> {
  type: 'window'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /**
   * The view mounted into this window, BY REFERENCE (`[[^^id]]` into the pool, or `[[file]]` naming a
   * composition). Reference-only, like every child position. ABSENT is an empty (or dormant) window that
   * still exists in the composition — a surface with nothing mounted, kept so it reopens.
   */
  content?: Ref<'mountable'>
  /**
   * The MAIN window (surface 0), the one the app opens into and the authority is co-located with.
   * Exactly one window in a composition is primary; the rest are secondary surfaces of the SAME
   * composition. Absent reads as not-primary. Surface 0 is symmetric — driven through the same interface
   * as any surface — so this flag names WHICH window is the entry, not a privileged code path.
   */
  primary?: boolean
  /**
   * What the window's OS title bar shows. Absent falls back to a host default (the workspace / content
   * name). A POSITION's title, like a container slot's `label`: it names the window, not whatever view
   * happens to be mounted in it.
   */
  title?: string
}

/** Host startup choice in the entry workspace's workspace-startup.yaml. */
export interface WorkspaceStartup {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** Initial layout, used until the user has a valid remembered composition choice. Omit for an empty start. */
  initialComposition?: Ref<'composition'>
}

export interface WorkspaceTemplate {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  path: string
  name: string
  description: string
  highlights?: string[]
  preview?: WorkspaceTemplatePreview
  /** Composition wikilink resolved from the created workspace, not the manifest. Omit for an empty start. */
  initialComposition?: string
}

export interface WorkspaceTemplateManifest {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  templates: WorkspaceTemplate[]
}

export interface WorkspaceTemplatePreview {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  axis?: string
  children?: WorkspaceTemplatePreview[]
  label?: string
  kind?: string
  weight?: number
}

export const KeyModifierValues = ['mod', 'ctrl', 'alt', 'shift'] as const

export const KeyNameValues = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'digit0', 'digit1', 'digit2', 'digit3', 'digit4', 'digit5', 'digit6', 'digit7', 'digit8', 'digit9', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10', 'f11', 'f12', 'arrowup', 'arrowdown', 'arrowleft', 'arrowright', 'enter', 'tab', 'escape', 'space', 'backspace', 'delete', 'home', 'end', 'pageup', 'pagedown', 'minus', 'equal', 'bracketleft', 'bracketright', 'backslash', 'semicolon', 'quote', 'backquote', 'comma', 'period', 'slash'] as const
