// Generated by @arsumbris/type-codegen. Do not edit by hand.
// Source: au-engine type-defs, repo `aup-workspace-sidebar`.

import type { ContainerProjection } from '@arsumbris/au-host-sdk'

/** A branded wikilink string. The brand records the referenced type-def name(s). */
export type Ref<T extends string> = string & { readonly __ref: T }

/** A branded wikilink to a type-def (the def axis of `T*`), distinct from an instance `Ref`. The brand records the def-axis bound. */
export type DefRef<T extends string> = string & { readonly __defRef: T }

export interface AupWorkspaceSidebar extends Omit<ContainerProjection, 'type'> {
  type: 'aup-workspace-sidebar'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /**
   * The one region — the sidebar's view area. Holds a container (a `column`) by reference; the rail
   * delegates all re-parenting to it and the column stacks views inside. Absent = an empty rail.
   * A bare `mountable*` — a containment position with no per-slot rules. `mountable` is the marker the
   * pool walk descends by; widen to `<mountable* | container-slot>` if the body ever needs `fixed` /
   * `admits` (the shape dock / tabs use).
   */
  body?: Ref<'mountable'>
}
