// Generated by @arsumbris/type-codegen. Do not edit by hand.
// Source: au-engine type-defs, repo `range`.

/** A branded wikilink string. The brand records the referenced type-def name(s). */
export type Ref<T extends string> = string & { readonly __ref: T }

/** A branded wikilink to a type-def (the def axis of `T*`), distinct from an instance `Ref`. The brand records the def-axis bound. */
export type DefRef<T extends string> = string & { readonly __defRef: T }

export interface Range {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface TextRange extends Omit<Range, 'type'> {
  type: 'text-range'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  from: number
  to: number
}
