// Generated by @arsumbris/type-codegen. Do not edit by hand.
// Source: au-engine type-defs, repo `bento`.

import type { ContainerNode, ContainerSlot, SpatialContainer } from '@arsumbris/au-host-sdk'

/** A branded wikilink string. The brand records the referenced type-def name(s). */
export type Ref<T extends string> = string & { readonly __ref: T }

/** A branded wikilink to a type-def (the def axis of `T*`), distinct from an instance `Ref`. The brand records the def-axis bound. */
export type DefRef<T extends string> = string & { readonly __defRef: T }

export interface Bento extends Omit<SpatialContainer, 'type'> {
  type: 'bento'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  root: Ref<'mountable'> | BentoSlot | BentoNodeBranch
}

export interface BentoNodeBase extends Omit<ContainerNode, 'type'> {
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export type BentoNode = BentoNodeBranch

export interface BentoNodeBranch extends Omit<BentoNodeBase, 'type'> {
  type: 'bento-node.branch'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  direction: 'row' | 'column'
  ratio: number
  children: Array<Ref<'mountable'> | BentoSlot | BentoNodeBranch>
}

/**
 * A bento pane position. Adds nothing to the shared slot: bento sizes its splits through
 * `bento-node.branch.ratio`, so it honours no size or collapse of its own.
 */
export interface BentoSlot extends Omit<ContainerSlot, 'type'> {
  type: 'bento-slot'
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}
