// Generated by @arsumbris/type-codegen. Do not edit by hand.
// Source: au-engine type-defs, repo `component-contract`.

/** A branded wikilink string. The brand records the referenced type-def name(s). */
export type Ref<T extends string> = string & { readonly __ref: T }

/** A branded wikilink to a type-def (the def axis of `T*`), distinct from an instance `Ref`. The brand records the def-axis bound. */
export type DefRef<T extends string> = string & { readonly __defRef: T }

/**
 * The open base for a component-set: a package implementing ui-component contracts. Real sets
 * are subtypes carrying a component-set-runtime-meta locator. A tag — no instances, no fields;
 * the active set is a per-machine stored id.
 */
export interface ComponentSet {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface ComponentSetRuntimeMeta {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** ESM entry that registers the set's elements, relative to the package root. */
  entry: string
  /** Contract version the set was built against; strict-equality gated at the handshake. */
  contractVersion: number
  /** The export the host calls to register elements; default `register`. */
  export?: string
  /** The ui-component contracts this set implements. Drives per-tag coverage and resolution. */
  provides: DefRef<'ui-component'>[]
  /** Token-declaration stylesheet(s) for the set's `--au-<component>-*` tokens; theming-pane discovers them. */
  customTokenEntry?: [string, ...Array<string>]
}

/**
 * The open base for a single UI component's INTERFACE. Contract-only — no persisted
 * instances; the type-def exists to drive CODEGEN (typed consumer props) and DISCOVERY
 * (which tags exist, which set provides each). The subtype's name IS the element tag.
 */
export interface UiComponent {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
}

export interface UiComponentMeta {
  type?: string
  /** The record's engine-assigned `^:` block id, present once addressed. Advisory, never validated. */
  '^'?: string
  /** CustomEvent names dispatched. MUST be composed + bubbling so they cross the shadow boundary. */
  events?: string[]
  /** Declared named content regions, realized as native shadow <slot name>. */
  slots?: string[]
  /** :state() custom-state names the component exposes, for theming and tooling. */
  states?: string[]
  /** ::part names exposed for structural overrides. Declared so theming can enumerate them. */
  parts?: string[]
  /**
   * Optional sample-composition HTML the gallery renders verbatim (the story/escape-hatch for
   * composites + grain-reduced containers auto-synthesis can't showcase).
   */
  preview?: string
}
